package com.drive.license.test.models

import drivelicensetest.composeapp.generated.resources.Res
import drivelicensetest.composeapp.generated.resources.question_1000
import drivelicensetest.composeapp.generated.resources.question_1000_answer_1
import drivelicensetest.composeapp.generated.resources.question_1000_answer_2
import drivelicensetest.composeapp.generated.resources.question_1000_answer_3
import drivelicensetest.composeapp.generated.resources.question_1000_true_answer
import drivelicensetest.composeapp.generated.resources.question_1001
import drivelicensetest.composeapp.generated.resources.question_1001_answer_1
import drivelicensetest.composeapp.generated.resources.question_1001_answer_2
import drivelicensetest.composeapp.generated.resources.question_1001_true_answer
import drivelicensetest.composeapp.generated.resources.question_1002
import drivelicensetest.composeapp.generated.resources.question_1002_answer_1
import drivelicensetest.composeapp.generated.resources.question_1002_answer_2
import drivelicensetest.composeapp.generated.resources.question_1002_answer_3
import drivelicensetest.composeapp.generated.resources.question_1002_true_answer
import drivelicensetest.composeapp.generated.resources.question_1003
import drivelicensetest.composeapp.generated.resources.question_1003_answer_1
import drivelicensetest.composeapp.generated.resources.question_1003_answer_2
import drivelicensetest.composeapp.generated.resources.question_1003_true_answer
import drivelicensetest.composeapp.generated.resources.question_1004
import drivelicensetest.composeapp.generated.resources.question_1004_answer_1
import drivelicensetest.composeapp.generated.resources.question_1004_answer_2
import drivelicensetest.composeapp.generated.resources.question_1004_answer_3
import drivelicensetest.composeapp.generated.resources.question_1004_true_answer
import drivelicensetest.composeapp.generated.resources.question_1005
import drivelicensetest.composeapp.generated.resources.question_1005_answer_1
import drivelicensetest.composeapp.generated.resources.question_1005_answer_2
import drivelicensetest.composeapp.generated.resources.question_1005_answer_3
import drivelicensetest.composeapp.generated.resources.question_1005_true_answer
import drivelicensetest.composeapp.generated.resources.question_1006
import drivelicensetest.composeapp.generated.resources.question_1006_answer_1
import drivelicensetest.composeapp.generated.resources.question_1006_answer_2
import drivelicensetest.composeapp.generated.resources.question_1006_answer_3
import drivelicensetest.composeapp.generated.resources.question_1006_true_answer
import drivelicensetest.composeapp.generated.resources.question_1007
import drivelicensetest.composeapp.generated.resources.question_1007_answer_1
import drivelicensetest.composeapp.generated.resources.question_1007_answer_2
import drivelicensetest.composeapp.generated.resources.question_1007_answer_3
import drivelicensetest.composeapp.generated.resources.question_1007_true_answer
import drivelicensetest.composeapp.generated.resources.question_1008
import drivelicensetest.composeapp.generated.resources.question_1008_answer_1
import drivelicensetest.composeapp.generated.resources.question_1008_answer_2
import drivelicensetest.composeapp.generated.resources.question_1008_answer_3
import drivelicensetest.composeapp.generated.resources.question_1008_true_answer
import drivelicensetest.composeapp.generated.resources.question_1009
import drivelicensetest.composeapp.generated.resources.question_1009_answer_1
import drivelicensetest.composeapp.generated.resources.question_1009_answer_2
import drivelicensetest.composeapp.generated.resources.question_1009_true_answer
import drivelicensetest.composeapp.generated.resources.question_1010
import drivelicensetest.composeapp.generated.resources.question_1010_answer_1
import drivelicensetest.composeapp.generated.resources.question_1010_answer_2
import drivelicensetest.composeapp.generated.resources.question_1010_answer_3
import drivelicensetest.composeapp.generated.resources.question_1010_true_answer
import drivelicensetest.composeapp.generated.resources.question_1011
import drivelicensetest.composeapp.generated.resources.question_1011_answer_1
import drivelicensetest.composeapp.generated.resources.question_1011_answer_2
import drivelicensetest.composeapp.generated.resources.question_1011_answer_3
import drivelicensetest.composeapp.generated.resources.question_1011_true_answer
import drivelicensetest.composeapp.generated.resources.question_1012
import drivelicensetest.composeapp.generated.resources.question_1012_answer_1
import drivelicensetest.composeapp.generated.resources.question_1012_answer_2
import drivelicensetest.composeapp.generated.resources.question_1012_answer_3
import drivelicensetest.composeapp.generated.resources.question_1012_true_answer
import drivelicensetest.composeapp.generated.resources.question_1013
import drivelicensetest.composeapp.generated.resources.question_1013_answer_1
import drivelicensetest.composeapp.generated.resources.question_1013_answer_2
import drivelicensetest.composeapp.generated.resources.question_1013_true_answer
import drivelicensetest.composeapp.generated.resources.question_1014
import drivelicensetest.composeapp.generated.resources.question_1014_answer_1
import drivelicensetest.composeapp.generated.resources.question_1014_answer_2
import drivelicensetest.composeapp.generated.resources.question_1014_answer_3
import drivelicensetest.composeapp.generated.resources.question_1014_true_answer
import drivelicensetest.composeapp.generated.resources.question_1015
import drivelicensetest.composeapp.generated.resources.question_1015_answer_1
import drivelicensetest.composeapp.generated.resources.question_1015_answer_2
import drivelicensetest.composeapp.generated.resources.question_1015_answer_3
import drivelicensetest.composeapp.generated.resources.question_1015_true_answer
import drivelicensetest.composeapp.generated.resources.question_1016
import drivelicensetest.composeapp.generated.resources.question_1016_answer_1
import drivelicensetest.composeapp.generated.resources.question_1016_answer_2
import drivelicensetest.composeapp.generated.resources.question_1016_true_answer
import drivelicensetest.composeapp.generated.resources.question_1017
import drivelicensetest.composeapp.generated.resources.question_1017_answer_1
import drivelicensetest.composeapp.generated.resources.question_1017_answer_2
import drivelicensetest.composeapp.generated.resources.question_1017_answer_3
import drivelicensetest.composeapp.generated.resources.question_1017_true_answer
import drivelicensetest.composeapp.generated.resources.question_1018
import drivelicensetest.composeapp.generated.resources.question_1018_answer_1
import drivelicensetest.composeapp.generated.resources.question_1018_answer_2
import drivelicensetest.composeapp.generated.resources.question_1018_answer_3
import drivelicensetest.composeapp.generated.resources.question_1018_true_answer
import drivelicensetest.composeapp.generated.resources.question_1019
import drivelicensetest.composeapp.generated.resources.question_1019_answer_1
import drivelicensetest.composeapp.generated.resources.question_1019_answer_2
import drivelicensetest.composeapp.generated.resources.question_1019_answer_3
import drivelicensetest.composeapp.generated.resources.question_1019_true_answer
import drivelicensetest.composeapp.generated.resources.question_1020
import drivelicensetest.composeapp.generated.resources.question_1020_answer_1
import drivelicensetest.composeapp.generated.resources.question_1020_answer_2
import drivelicensetest.composeapp.generated.resources.question_1020_answer_3
import drivelicensetest.composeapp.generated.resources.question_1020_true_answer
import drivelicensetest.composeapp.generated.resources.question_1021
import drivelicensetest.composeapp.generated.resources.question_1021_answer_1
import drivelicensetest.composeapp.generated.resources.question_1021_answer_2
import drivelicensetest.composeapp.generated.resources.question_1021_answer_3
import drivelicensetest.composeapp.generated.resources.question_1021_true_answer
import drivelicensetest.composeapp.generated.resources.question_1022
import drivelicensetest.composeapp.generated.resources.question_1022_answer_1
import drivelicensetest.composeapp.generated.resources.question_1022_answer_2
import drivelicensetest.composeapp.generated.resources.question_1022_answer_3
import drivelicensetest.composeapp.generated.resources.question_1022_true_answer
import drivelicensetest.composeapp.generated.resources.question_1023
import drivelicensetest.composeapp.generated.resources.question_1023_answer_1
import drivelicensetest.composeapp.generated.resources.question_1023_answer_2
import drivelicensetest.composeapp.generated.resources.question_1023_answer_3
import drivelicensetest.composeapp.generated.resources.question_1023_true_answer
import drivelicensetest.composeapp.generated.resources.question_1024
import drivelicensetest.composeapp.generated.resources.question_1024_answer_1
import drivelicensetest.composeapp.generated.resources.question_1024_answer_2
import drivelicensetest.composeapp.generated.resources.question_1024_true_answer
import drivelicensetest.composeapp.generated.resources.question_1025
import drivelicensetest.composeapp.generated.resources.question_1025_answer_1
import drivelicensetest.composeapp.generated.resources.question_1025_answer_2
import drivelicensetest.composeapp.generated.resources.question_1025_answer_3
import drivelicensetest.composeapp.generated.resources.question_1025_true_answer
import drivelicensetest.composeapp.generated.resources.question_1026
import drivelicensetest.composeapp.generated.resources.question_1026_answer_1
import drivelicensetest.composeapp.generated.resources.question_1026_answer_2
import drivelicensetest.composeapp.generated.resources.question_1026_answer_3
import drivelicensetest.composeapp.generated.resources.question_1026_true_answer
import drivelicensetest.composeapp.generated.resources.question_1027
import drivelicensetest.composeapp.generated.resources.question_1027_answer_1
import drivelicensetest.composeapp.generated.resources.question_1027_answer_2
import drivelicensetest.composeapp.generated.resources.question_1027_answer_3
import drivelicensetest.composeapp.generated.resources.question_1027_true_answer
import drivelicensetest.composeapp.generated.resources.question_1028
import drivelicensetest.composeapp.generated.resources.question_1028_answer_1
import drivelicensetest.composeapp.generated.resources.question_1028_answer_2
import drivelicensetest.composeapp.generated.resources.question_1028_answer_3
import drivelicensetest.composeapp.generated.resources.question_1028_true_answer
import drivelicensetest.composeapp.generated.resources.question_1029
import drivelicensetest.composeapp.generated.resources.question_1029_answer_1
import drivelicensetest.composeapp.generated.resources.question_1029_answer_2
import drivelicensetest.composeapp.generated.resources.question_1029_answer_3
import drivelicensetest.composeapp.generated.resources.question_1029_true_answer
import drivelicensetest.composeapp.generated.resources.question_1030
import drivelicensetest.composeapp.generated.resources.question_1030_answer_1
import drivelicensetest.composeapp.generated.resources.question_1030_answer_2
import drivelicensetest.composeapp.generated.resources.question_1030_true_answer
import drivelicensetest.composeapp.generated.resources.question_1031
import drivelicensetest.composeapp.generated.resources.question_1031_answer_1
import drivelicensetest.composeapp.generated.resources.question_1031_answer_2
import drivelicensetest.composeapp.generated.resources.question_1031_answer_3
import drivelicensetest.composeapp.generated.resources.question_1031_true_answer
import drivelicensetest.composeapp.generated.resources.question_1032
import drivelicensetest.composeapp.generated.resources.question_1032_answer_1
import drivelicensetest.composeapp.generated.resources.question_1032_answer_2
import drivelicensetest.composeapp.generated.resources.question_1032_true_answer
import drivelicensetest.composeapp.generated.resources.question_1033
import drivelicensetest.composeapp.generated.resources.question_1033_answer_1
import drivelicensetest.composeapp.generated.resources.question_1033_answer_2
import drivelicensetest.composeapp.generated.resources.question_1033_answer_3
import drivelicensetest.composeapp.generated.resources.question_1033_true_answer
import drivelicensetest.composeapp.generated.resources.question_1034
import drivelicensetest.composeapp.generated.resources.question_1034_answer_1
import drivelicensetest.composeapp.generated.resources.question_1034_answer_2
import drivelicensetest.composeapp.generated.resources.question_1034_answer_3
import drivelicensetest.composeapp.generated.resources.question_1034_true_answer
import drivelicensetest.composeapp.generated.resources.question_1035
import drivelicensetest.composeapp.generated.resources.question_1035_answer_1
import drivelicensetest.composeapp.generated.resources.question_1035_answer_2
import drivelicensetest.composeapp.generated.resources.question_1035_true_answer
import drivelicensetest.composeapp.generated.resources.question_1036
import drivelicensetest.composeapp.generated.resources.question_1036_answer_1
import drivelicensetest.composeapp.generated.resources.question_1036_answer_2
import drivelicensetest.composeapp.generated.resources.question_1036_true_answer
import drivelicensetest.composeapp.generated.resources.question_1037
import drivelicensetest.composeapp.generated.resources.question_1037_answer_1
import drivelicensetest.composeapp.generated.resources.question_1037_answer_2
import drivelicensetest.composeapp.generated.resources.question_1037_true_answer
import drivelicensetest.composeapp.generated.resources.question_1038
import drivelicensetest.composeapp.generated.resources.question_1038_answer_1
import drivelicensetest.composeapp.generated.resources.question_1038_answer_2
import drivelicensetest.composeapp.generated.resources.question_1038_true_answer
import drivelicensetest.composeapp.generated.resources.question_1039
import drivelicensetest.composeapp.generated.resources.question_1039_answer_1
import drivelicensetest.composeapp.generated.resources.question_1039_answer_2
import drivelicensetest.composeapp.generated.resources.question_1039_answer_3
import drivelicensetest.composeapp.generated.resources.question_1039_true_answer
import drivelicensetest.composeapp.generated.resources.question_1040
import drivelicensetest.composeapp.generated.resources.question_1040_answer_1
import drivelicensetest.composeapp.generated.resources.question_1040_answer_2
import drivelicensetest.composeapp.generated.resources.question_1040_answer_3
import drivelicensetest.composeapp.generated.resources.question_1040_true_answer
import drivelicensetest.composeapp.generated.resources.question_1041
import drivelicensetest.composeapp.generated.resources.question_1041_answer_1
import drivelicensetest.composeapp.generated.resources.question_1041_answer_2
import drivelicensetest.composeapp.generated.resources.question_1041_true_answer
import drivelicensetest.composeapp.generated.resources.question_1042
import drivelicensetest.composeapp.generated.resources.question_1042_answer_1
import drivelicensetest.composeapp.generated.resources.question_1042_answer_2
import drivelicensetest.composeapp.generated.resources.question_1042_answer_3
import drivelicensetest.composeapp.generated.resources.question_1042_true_answer
import drivelicensetest.composeapp.generated.resources.question_1043
import drivelicensetest.composeapp.generated.resources.question_1043_answer_1
import drivelicensetest.composeapp.generated.resources.question_1043_answer_2
import drivelicensetest.composeapp.generated.resources.question_1043_answer_3
import drivelicensetest.composeapp.generated.resources.question_1043_true_answer
import drivelicensetest.composeapp.generated.resources.question_918
import drivelicensetest.composeapp.generated.resources.question_918_answer_1
import drivelicensetest.composeapp.generated.resources.question_918_answer_2
import drivelicensetest.composeapp.generated.resources.question_918_answer_3
import drivelicensetest.composeapp.generated.resources.question_918_true_answer
import drivelicensetest.composeapp.generated.resources.question_919
import drivelicensetest.composeapp.generated.resources.question_919_answer_1
import drivelicensetest.composeapp.generated.resources.question_919_answer_2
import drivelicensetest.composeapp.generated.resources.question_919_answer_3
import drivelicensetest.composeapp.generated.resources.question_919_true_answer
import drivelicensetest.composeapp.generated.resources.question_920
import drivelicensetest.composeapp.generated.resources.question_920_answer_1
import drivelicensetest.composeapp.generated.resources.question_920_answer_2
import drivelicensetest.composeapp.generated.resources.question_920_answer_3
import drivelicensetest.composeapp.generated.resources.question_920_answer_4
import drivelicensetest.composeapp.generated.resources.question_920_true_answer
import drivelicensetest.composeapp.generated.resources.question_921
import drivelicensetest.composeapp.generated.resources.question_921_answer_1
import drivelicensetest.composeapp.generated.resources.question_921_answer_2
import drivelicensetest.composeapp.generated.resources.question_921_answer_3
import drivelicensetest.composeapp.generated.resources.question_921_true_answer
import drivelicensetest.composeapp.generated.resources.question_922
import drivelicensetest.composeapp.generated.resources.question_922_answer_1
import drivelicensetest.composeapp.generated.resources.question_922_answer_2
import drivelicensetest.composeapp.generated.resources.question_922_true_answer
import drivelicensetest.composeapp.generated.resources.question_923
import drivelicensetest.composeapp.generated.resources.question_923_answer_1
import drivelicensetest.composeapp.generated.resources.question_923_answer_2
import drivelicensetest.composeapp.generated.resources.question_923_answer_3
import drivelicensetest.composeapp.generated.resources.question_923_true_answer
import drivelicensetest.composeapp.generated.resources.question_924
import drivelicensetest.composeapp.generated.resources.question_924_answer_1
import drivelicensetest.composeapp.generated.resources.question_924_answer_2
import drivelicensetest.composeapp.generated.resources.question_924_answer_3
import drivelicensetest.composeapp.generated.resources.question_924_true_answer
import drivelicensetest.composeapp.generated.resources.question_925
import drivelicensetest.composeapp.generated.resources.question_925_answer_1
import drivelicensetest.composeapp.generated.resources.question_925_answer_2
import drivelicensetest.composeapp.generated.resources.question_925_answer_3
import drivelicensetest.composeapp.generated.resources.question_925_true_answer
import drivelicensetest.composeapp.generated.resources.question_926
import drivelicensetest.composeapp.generated.resources.question_926_answer_1
import drivelicensetest.composeapp.generated.resources.question_926_answer_2
import drivelicensetest.composeapp.generated.resources.question_926_answer_3
import drivelicensetest.composeapp.generated.resources.question_926_true_answer
import drivelicensetest.composeapp.generated.resources.question_927
import drivelicensetest.composeapp.generated.resources.question_927_answer_1
import drivelicensetest.composeapp.generated.resources.question_927_answer_2
import drivelicensetest.composeapp.generated.resources.question_927_answer_3
import drivelicensetest.composeapp.generated.resources.question_927_true_answer
import drivelicensetest.composeapp.generated.resources.question_928
import drivelicensetest.composeapp.generated.resources.question_928_answer_1
import drivelicensetest.composeapp.generated.resources.question_928_answer_2
import drivelicensetest.composeapp.generated.resources.question_928_answer_3
import drivelicensetest.composeapp.generated.resources.question_928_true_answer
import drivelicensetest.composeapp.generated.resources.question_929
import drivelicensetest.composeapp.generated.resources.question_929_answer_1
import drivelicensetest.composeapp.generated.resources.question_929_answer_2
import drivelicensetest.composeapp.generated.resources.question_929_answer_3
import drivelicensetest.composeapp.generated.resources.question_929_true_answer
import drivelicensetest.composeapp.generated.resources.question_930
import drivelicensetest.composeapp.generated.resources.question_930_answer_1
import drivelicensetest.composeapp.generated.resources.question_930_answer_2
import drivelicensetest.composeapp.generated.resources.question_930_answer_3
import drivelicensetest.composeapp.generated.resources.question_930_answer_4
import drivelicensetest.composeapp.generated.resources.question_930_true_answer
import drivelicensetest.composeapp.generated.resources.question_931
import drivelicensetest.composeapp.generated.resources.question_931_answer_1
import drivelicensetest.composeapp.generated.resources.question_931_answer_2
import drivelicensetest.composeapp.generated.resources.question_931_answer_3
import drivelicensetest.composeapp.generated.resources.question_931_true_answer
import drivelicensetest.composeapp.generated.resources.question_932
import drivelicensetest.composeapp.generated.resources.question_932_answer_1
import drivelicensetest.composeapp.generated.resources.question_932_answer_2
import drivelicensetest.composeapp.generated.resources.question_932_true_answer
import drivelicensetest.composeapp.generated.resources.question_933
import drivelicensetest.composeapp.generated.resources.question_933_answer_1
import drivelicensetest.composeapp.generated.resources.question_933_answer_2
import drivelicensetest.composeapp.generated.resources.question_933_true_answer
import drivelicensetest.composeapp.generated.resources.question_934
import drivelicensetest.composeapp.generated.resources.question_934_answer_1
import drivelicensetest.composeapp.generated.resources.question_934_answer_2
import drivelicensetest.composeapp.generated.resources.question_934_true_answer
import drivelicensetest.composeapp.generated.resources.question_935
import drivelicensetest.composeapp.generated.resources.question_935_answer_1
import drivelicensetest.composeapp.generated.resources.question_935_answer_2
import drivelicensetest.composeapp.generated.resources.question_935_answer_3
import drivelicensetest.composeapp.generated.resources.question_935_true_answer
import drivelicensetest.composeapp.generated.resources.question_936
import drivelicensetest.composeapp.generated.resources.question_936_answer_1
import drivelicensetest.composeapp.generated.resources.question_936_answer_2
import drivelicensetest.composeapp.generated.resources.question_936_true_answer
import drivelicensetest.composeapp.generated.resources.question_937
import drivelicensetest.composeapp.generated.resources.question_937_answer_1
import drivelicensetest.composeapp.generated.resources.question_937_answer_2
import drivelicensetest.composeapp.generated.resources.question_937_true_answer
import drivelicensetest.composeapp.generated.resources.question_938
import drivelicensetest.composeapp.generated.resources.question_938_answer_1
import drivelicensetest.composeapp.generated.resources.question_938_answer_2
import drivelicensetest.composeapp.generated.resources.question_938_answer_3
import drivelicensetest.composeapp.generated.resources.question_938_true_answer
import drivelicensetest.composeapp.generated.resources.question_939
import drivelicensetest.composeapp.generated.resources.question_939_answer_1
import drivelicensetest.composeapp.generated.resources.question_939_answer_2
import drivelicensetest.composeapp.generated.resources.question_939_true_answer
import drivelicensetest.composeapp.generated.resources.question_940
import drivelicensetest.composeapp.generated.resources.question_940_answer_1
import drivelicensetest.composeapp.generated.resources.question_940_answer_2
import drivelicensetest.composeapp.generated.resources.question_940_answer_3
import drivelicensetest.composeapp.generated.resources.question_940_answer_4
import drivelicensetest.composeapp.generated.resources.question_940_true_answer
import drivelicensetest.composeapp.generated.resources.question_941
import drivelicensetest.composeapp.generated.resources.question_941_answer_1
import drivelicensetest.composeapp.generated.resources.question_941_answer_2
import drivelicensetest.composeapp.generated.resources.question_941_true_answer
import drivelicensetest.composeapp.generated.resources.question_942
import drivelicensetest.composeapp.generated.resources.question_942_answer_1
import drivelicensetest.composeapp.generated.resources.question_942_answer_2
import drivelicensetest.composeapp.generated.resources.question_942_true_answer
import drivelicensetest.composeapp.generated.resources.question_943
import drivelicensetest.composeapp.generated.resources.question_943_answer_1
import drivelicensetest.composeapp.generated.resources.question_943_answer_2
import drivelicensetest.composeapp.generated.resources.question_943_answer_3
import drivelicensetest.composeapp.generated.resources.question_943_true_answer
import drivelicensetest.composeapp.generated.resources.question_944
import drivelicensetest.composeapp.generated.resources.question_944_answer_1
import drivelicensetest.composeapp.generated.resources.question_944_answer_2
import drivelicensetest.composeapp.generated.resources.question_944_answer_3
import drivelicensetest.composeapp.generated.resources.question_944_true_answer
import drivelicensetest.composeapp.generated.resources.question_945
import drivelicensetest.composeapp.generated.resources.question_945_answer_1
import drivelicensetest.composeapp.generated.resources.question_945_answer_2
import drivelicensetest.composeapp.generated.resources.question_945_true_answer
import drivelicensetest.composeapp.generated.resources.question_946
import drivelicensetest.composeapp.generated.resources.question_946_answer_1
import drivelicensetest.composeapp.generated.resources.question_946_answer_2
import drivelicensetest.composeapp.generated.resources.question_946_answer_3
import drivelicensetest.composeapp.generated.resources.question_946_true_answer
import drivelicensetest.composeapp.generated.resources.question_947
import drivelicensetest.composeapp.generated.resources.question_947_answer_1
import drivelicensetest.composeapp.generated.resources.question_947_answer_2
import drivelicensetest.composeapp.generated.resources.question_947_answer_3
import drivelicensetest.composeapp.generated.resources.question_947_true_answer
import drivelicensetest.composeapp.generated.resources.question_948
import drivelicensetest.composeapp.generated.resources.question_948_answer_1
import drivelicensetest.composeapp.generated.resources.question_948_answer_2
import drivelicensetest.composeapp.generated.resources.question_948_answer_3
import drivelicensetest.composeapp.generated.resources.question_948_true_answer
import drivelicensetest.composeapp.generated.resources.question_949
import drivelicensetest.composeapp.generated.resources.question_949_answer_1
import drivelicensetest.composeapp.generated.resources.question_949_answer_2
import drivelicensetest.composeapp.generated.resources.question_949_true_answer
import drivelicensetest.composeapp.generated.resources.question_950
import drivelicensetest.composeapp.generated.resources.question_950_answer_1
import drivelicensetest.composeapp.generated.resources.question_950_answer_2
import drivelicensetest.composeapp.generated.resources.question_950_answer_3
import drivelicensetest.composeapp.generated.resources.question_950_true_answer
import drivelicensetest.composeapp.generated.resources.question_951
import drivelicensetest.composeapp.generated.resources.question_951_answer_1
import drivelicensetest.composeapp.generated.resources.question_951_answer_2
import drivelicensetest.composeapp.generated.resources.question_951_answer_3
import drivelicensetest.composeapp.generated.resources.question_951_true_answer
import drivelicensetest.composeapp.generated.resources.question_952
import drivelicensetest.composeapp.generated.resources.question_952_answer_1
import drivelicensetest.composeapp.generated.resources.question_952_answer_2
import drivelicensetest.composeapp.generated.resources.question_952_true_answer
import drivelicensetest.composeapp.generated.resources.question_953
import drivelicensetest.composeapp.generated.resources.question_953_answer_1
import drivelicensetest.composeapp.generated.resources.question_953_answer_2
import drivelicensetest.composeapp.generated.resources.question_953_true_answer
import drivelicensetest.composeapp.generated.resources.question_954
import drivelicensetest.composeapp.generated.resources.question_954_answer_1
import drivelicensetest.composeapp.generated.resources.question_954_answer_2
import drivelicensetest.composeapp.generated.resources.question_954_answer_3
import drivelicensetest.composeapp.generated.resources.question_954_true_answer
import drivelicensetest.composeapp.generated.resources.question_955
import drivelicensetest.composeapp.generated.resources.question_955_answer_1
import drivelicensetest.composeapp.generated.resources.question_955_answer_2
import drivelicensetest.composeapp.generated.resources.question_955_answer_3
import drivelicensetest.composeapp.generated.resources.question_955_answer_4
import drivelicensetest.composeapp.generated.resources.question_955_true_answer
import drivelicensetest.composeapp.generated.resources.question_956
import drivelicensetest.composeapp.generated.resources.question_956_answer_1
import drivelicensetest.composeapp.generated.resources.question_956_answer_2
import drivelicensetest.composeapp.generated.resources.question_956_answer_3
import drivelicensetest.composeapp.generated.resources.question_956_answer_4
import drivelicensetest.composeapp.generated.resources.question_956_true_answer
import drivelicensetest.composeapp.generated.resources.question_957
import drivelicensetest.composeapp.generated.resources.question_957_answer_1
import drivelicensetest.composeapp.generated.resources.question_957_answer_2
import drivelicensetest.composeapp.generated.resources.question_957_answer_3
import drivelicensetest.composeapp.generated.resources.question_957_true_answer
import drivelicensetest.composeapp.generated.resources.question_958
import drivelicensetest.composeapp.generated.resources.question_958_answer_1
import drivelicensetest.composeapp.generated.resources.question_958_answer_2
import drivelicensetest.composeapp.generated.resources.question_958_answer_3
import drivelicensetest.composeapp.generated.resources.question_958_true_answer
import drivelicensetest.composeapp.generated.resources.question_959
import drivelicensetest.composeapp.generated.resources.question_959_answer_1
import drivelicensetest.composeapp.generated.resources.question_959_answer_2
import drivelicensetest.composeapp.generated.resources.question_959_answer_3
import drivelicensetest.composeapp.generated.resources.question_959_answer_4
import drivelicensetest.composeapp.generated.resources.question_959_answer_5
import drivelicensetest.composeapp.generated.resources.question_959_true_answer
import drivelicensetest.composeapp.generated.resources.question_960
import drivelicensetest.composeapp.generated.resources.question_960_answer_1
import drivelicensetest.composeapp.generated.resources.question_960_answer_2
import drivelicensetest.composeapp.generated.resources.question_960_answer_3
import drivelicensetest.composeapp.generated.resources.question_960_true_answer
import drivelicensetest.composeapp.generated.resources.question_961
import drivelicensetest.composeapp.generated.resources.question_961_answer_1
import drivelicensetest.composeapp.generated.resources.question_961_answer_2
import drivelicensetest.composeapp.generated.resources.question_961_answer_3
import drivelicensetest.composeapp.generated.resources.question_961_answer_4
import drivelicensetest.composeapp.generated.resources.question_961_true_answer
import drivelicensetest.composeapp.generated.resources.question_962
import drivelicensetest.composeapp.generated.resources.question_962_answer_1
import drivelicensetest.composeapp.generated.resources.question_962_answer_2
import drivelicensetest.composeapp.generated.resources.question_962_answer_3
import drivelicensetest.composeapp.generated.resources.question_962_true_answer
import drivelicensetest.composeapp.generated.resources.question_963
import drivelicensetest.composeapp.generated.resources.question_963_answer_1
import drivelicensetest.composeapp.generated.resources.question_963_answer_2
import drivelicensetest.composeapp.generated.resources.question_963_answer_3
import drivelicensetest.composeapp.generated.resources.question_963_true_answer
import drivelicensetest.composeapp.generated.resources.question_964
import drivelicensetest.composeapp.generated.resources.question_964_answer_1
import drivelicensetest.composeapp.generated.resources.question_964_answer_2
import drivelicensetest.composeapp.generated.resources.question_964_answer_3
import drivelicensetest.composeapp.generated.resources.question_964_answer_4
import drivelicensetest.composeapp.generated.resources.question_964_true_answer
import drivelicensetest.composeapp.generated.resources.question_965
import drivelicensetest.composeapp.generated.resources.question_965_answer_1
import drivelicensetest.composeapp.generated.resources.question_965_answer_2
import drivelicensetest.composeapp.generated.resources.question_965_answer_3
import drivelicensetest.composeapp.generated.resources.question_965_answer_4
import drivelicensetest.composeapp.generated.resources.question_965_true_answer
import drivelicensetest.composeapp.generated.resources.question_966
import drivelicensetest.composeapp.generated.resources.question_966_answer_1
import drivelicensetest.composeapp.generated.resources.question_966_answer_2
import drivelicensetest.composeapp.generated.resources.question_966_answer_3
import drivelicensetest.composeapp.generated.resources.question_966_true_answer
import drivelicensetest.composeapp.generated.resources.question_967
import drivelicensetest.composeapp.generated.resources.question_967_answer_1
import drivelicensetest.composeapp.generated.resources.question_967_answer_2
import drivelicensetest.composeapp.generated.resources.question_967_answer_3
import drivelicensetest.composeapp.generated.resources.question_967_answer_4
import drivelicensetest.composeapp.generated.resources.question_967_true_answer
import drivelicensetest.composeapp.generated.resources.question_968
import drivelicensetest.composeapp.generated.resources.question_968_answer_1
import drivelicensetest.composeapp.generated.resources.question_968_answer_2
import drivelicensetest.composeapp.generated.resources.question_968_answer_3
import drivelicensetest.composeapp.generated.resources.question_968_true_answer
import drivelicensetest.composeapp.generated.resources.question_969
import drivelicensetest.composeapp.generated.resources.question_969_answer_1
import drivelicensetest.composeapp.generated.resources.question_969_answer_2
import drivelicensetest.composeapp.generated.resources.question_969_answer_3
import drivelicensetest.composeapp.generated.resources.question_969_true_answer
import drivelicensetest.composeapp.generated.resources.question_970
import drivelicensetest.composeapp.generated.resources.question_970_answer_1
import drivelicensetest.composeapp.generated.resources.question_970_answer_2
import drivelicensetest.composeapp.generated.resources.question_970_answer_3
import drivelicensetest.composeapp.generated.resources.question_970_true_answer
import drivelicensetest.composeapp.generated.resources.question_971
import drivelicensetest.composeapp.generated.resources.question_971_answer_1
import drivelicensetest.composeapp.generated.resources.question_971_answer_2
import drivelicensetest.composeapp.generated.resources.question_971_answer_3
import drivelicensetest.composeapp.generated.resources.question_971_answer_4
import drivelicensetest.composeapp.generated.resources.question_971_true_answer
import drivelicensetest.composeapp.generated.resources.question_972
import drivelicensetest.composeapp.generated.resources.question_972_answer_1
import drivelicensetest.composeapp.generated.resources.question_972_answer_2
import drivelicensetest.composeapp.generated.resources.question_972_answer_3
import drivelicensetest.composeapp.generated.resources.question_972_true_answer
import drivelicensetest.composeapp.generated.resources.question_973
import drivelicensetest.composeapp.generated.resources.question_973_answer_1
import drivelicensetest.composeapp.generated.resources.question_973_answer_2
import drivelicensetest.composeapp.generated.resources.question_973_answer_3
import drivelicensetest.composeapp.generated.resources.question_973_true_answer
import drivelicensetest.composeapp.generated.resources.question_974
import drivelicensetest.composeapp.generated.resources.question_974_answer_1
import drivelicensetest.composeapp.generated.resources.question_974_answer_2
import drivelicensetest.composeapp.generated.resources.question_974_answer_3
import drivelicensetest.composeapp.generated.resources.question_974_true_answer
import drivelicensetest.composeapp.generated.resources.question_975
import drivelicensetest.composeapp.generated.resources.question_975_answer_1
import drivelicensetest.composeapp.generated.resources.question_975_answer_2
import drivelicensetest.composeapp.generated.resources.question_975_answer_3
import drivelicensetest.composeapp.generated.resources.question_975_true_answer
import drivelicensetest.composeapp.generated.resources.question_976
import drivelicensetest.composeapp.generated.resources.question_976_answer_1
import drivelicensetest.composeapp.generated.resources.question_976_answer_2
import drivelicensetest.composeapp.generated.resources.question_976_answer_3
import drivelicensetest.composeapp.generated.resources.question_976_true_answer
import drivelicensetest.composeapp.generated.resources.question_977
import drivelicensetest.composeapp.generated.resources.question_977_answer_1
import drivelicensetest.composeapp.generated.resources.question_977_answer_2
import drivelicensetest.composeapp.generated.resources.question_977_true_answer
import drivelicensetest.composeapp.generated.resources.question_978
import drivelicensetest.composeapp.generated.resources.question_978_answer_1
import drivelicensetest.composeapp.generated.resources.question_978_answer_2
import drivelicensetest.composeapp.generated.resources.question_978_answer_3
import drivelicensetest.composeapp.generated.resources.question_978_answer_4
import drivelicensetest.composeapp.generated.resources.question_978_true_answer
import drivelicensetest.composeapp.generated.resources.question_979
import drivelicensetest.composeapp.generated.resources.question_979_answer_1
import drivelicensetest.composeapp.generated.resources.question_979_answer_2
import drivelicensetest.composeapp.generated.resources.question_979_true_answer
import drivelicensetest.composeapp.generated.resources.question_980
import drivelicensetest.composeapp.generated.resources.question_980_answer_1
import drivelicensetest.composeapp.generated.resources.question_980_answer_2
import drivelicensetest.composeapp.generated.resources.question_980_true_answer
import drivelicensetest.composeapp.generated.resources.question_981
import drivelicensetest.composeapp.generated.resources.question_981_answer_1
import drivelicensetest.composeapp.generated.resources.question_981_answer_2
import drivelicensetest.composeapp.generated.resources.question_981_true_answer
import drivelicensetest.composeapp.generated.resources.question_982
import drivelicensetest.composeapp.generated.resources.question_982_answer_1
import drivelicensetest.composeapp.generated.resources.question_982_answer_2
import drivelicensetest.composeapp.generated.resources.question_982_true_answer
import drivelicensetest.composeapp.generated.resources.question_983
import drivelicensetest.composeapp.generated.resources.question_983_answer_1
import drivelicensetest.composeapp.generated.resources.question_983_answer_2
import drivelicensetest.composeapp.generated.resources.question_983_answer_3
import drivelicensetest.composeapp.generated.resources.question_983_answer_4
import drivelicensetest.composeapp.generated.resources.question_983_true_answer
import drivelicensetest.composeapp.generated.resources.question_984
import drivelicensetest.composeapp.generated.resources.question_984_answer_1
import drivelicensetest.composeapp.generated.resources.question_984_answer_2
import drivelicensetest.composeapp.generated.resources.question_984_answer_3
import drivelicensetest.composeapp.generated.resources.question_984_answer_4
import drivelicensetest.composeapp.generated.resources.question_984_true_answer
import drivelicensetest.composeapp.generated.resources.question_985
import drivelicensetest.composeapp.generated.resources.question_985_answer_1
import drivelicensetest.composeapp.generated.resources.question_985_answer_2
import drivelicensetest.composeapp.generated.resources.question_985_answer_3
import drivelicensetest.composeapp.generated.resources.question_985_answer_4
import drivelicensetest.composeapp.generated.resources.question_985_true_answer
import drivelicensetest.composeapp.generated.resources.question_986
import drivelicensetest.composeapp.generated.resources.question_986_answer_1
import drivelicensetest.composeapp.generated.resources.question_986_answer_2
import drivelicensetest.composeapp.generated.resources.question_986_true_answer
import drivelicensetest.composeapp.generated.resources.question_987
import drivelicensetest.composeapp.generated.resources.question_987_answer_1
import drivelicensetest.composeapp.generated.resources.question_987_answer_2
import drivelicensetest.composeapp.generated.resources.question_987_answer_3
import drivelicensetest.composeapp.generated.resources.question_987_true_answer
import drivelicensetest.composeapp.generated.resources.question_988
import drivelicensetest.composeapp.generated.resources.question_988_answer_1
import drivelicensetest.composeapp.generated.resources.question_988_answer_2
import drivelicensetest.composeapp.generated.resources.question_988_answer_3
import drivelicensetest.composeapp.generated.resources.question_988_true_answer
import drivelicensetest.composeapp.generated.resources.question_989
import drivelicensetest.composeapp.generated.resources.question_989_answer_1
import drivelicensetest.composeapp.generated.resources.question_989_answer_2
import drivelicensetest.composeapp.generated.resources.question_989_answer_3
import drivelicensetest.composeapp.generated.resources.question_989_true_answer
import drivelicensetest.composeapp.generated.resources.question_990
import drivelicensetest.composeapp.generated.resources.question_990_answer_1
import drivelicensetest.composeapp.generated.resources.question_990_answer_2
import drivelicensetest.composeapp.generated.resources.question_990_true_answer
import drivelicensetest.composeapp.generated.resources.question_991
import drivelicensetest.composeapp.generated.resources.question_991_answer_1
import drivelicensetest.composeapp.generated.resources.question_991_answer_2
import drivelicensetest.composeapp.generated.resources.question_991_answer_3
import drivelicensetest.composeapp.generated.resources.question_991_true_answer
import drivelicensetest.composeapp.generated.resources.question_992
import drivelicensetest.composeapp.generated.resources.question_992_answer_1
import drivelicensetest.composeapp.generated.resources.question_992_answer_2
import drivelicensetest.composeapp.generated.resources.question_992_answer_3
import drivelicensetest.composeapp.generated.resources.question_992_true_answer
import drivelicensetest.composeapp.generated.resources.question_993
import drivelicensetest.composeapp.generated.resources.question_993_answer_1
import drivelicensetest.composeapp.generated.resources.question_993_answer_2
import drivelicensetest.composeapp.generated.resources.question_993_answer_3
import drivelicensetest.composeapp.generated.resources.question_993_true_answer
import drivelicensetest.composeapp.generated.resources.question_994
import drivelicensetest.composeapp.generated.resources.question_994_answer_1
import drivelicensetest.composeapp.generated.resources.question_994_answer_2
import drivelicensetest.composeapp.generated.resources.question_994_true_answer
import drivelicensetest.composeapp.generated.resources.question_995
import drivelicensetest.composeapp.generated.resources.question_995_answer_1
import drivelicensetest.composeapp.generated.resources.question_995_answer_2
import drivelicensetest.composeapp.generated.resources.question_995_answer_3
import drivelicensetest.composeapp.generated.resources.question_995_true_answer
import drivelicensetest.composeapp.generated.resources.question_996
import drivelicensetest.composeapp.generated.resources.question_996_answer_1
import drivelicensetest.composeapp.generated.resources.question_996_answer_2
import drivelicensetest.composeapp.generated.resources.question_996_true_answer
import drivelicensetest.composeapp.generated.resources.question_997
import drivelicensetest.composeapp.generated.resources.question_997_answer_1
import drivelicensetest.composeapp.generated.resources.question_997_answer_2
import drivelicensetest.composeapp.generated.resources.question_997_true_answer
import drivelicensetest.composeapp.generated.resources.question_998
import drivelicensetest.composeapp.generated.resources.question_998_answer_1
import drivelicensetest.composeapp.generated.resources.question_998_answer_2
import drivelicensetest.composeapp.generated.resources.question_998_answer_3
import drivelicensetest.composeapp.generated.resources.question_998_answer_4
import drivelicensetest.composeapp.generated.resources.question_998_true_answer
import drivelicensetest.composeapp.generated.resources.question_999
import drivelicensetest.composeapp.generated.resources.question_999_answer_1
import drivelicensetest.composeapp.generated.resources.question_999_answer_2
import drivelicensetest.composeapp.generated.resources.question_999_true_answer

class QuestionGroup9 {

    private val questionsGroup9 = listOf(
        Question(
            question = Res.string.question_918,
            image = "question918_image.png",
            answers = listOf(
                Res.string.question_918_answer_1,
                Res.string.question_918_answer_2,
                Res.string.question_918_answer_3
            ),
            trueAnswer = Res.string.question_918_true_answer
        ),
        Question(
            question = Res.string.question_919,
            image = "question919_image.png",
            answers = listOf(
                Res.string.question_919_answer_1,
                Res.string.question_919_answer_2,
                Res.string.question_919_answer_3
            ),
            trueAnswer = Res.string.question_919_true_answer
        ),

        Question(
            question = Res.string.question_920,
            image = "question920_image.png",
            answers = listOf(
                Res.string.question_920_answer_1,
                Res.string.question_920_answer_2,
                Res.string.question_920_answer_3,
                Res.string.question_920_answer_4
            ),
            trueAnswer = Res.string.question_920_true_answer
        ),

        Question(
            question = Res.string.question_921,
            image = "question921_image.png",
            answers = listOf(
                Res.string.question_921_answer_1,
                Res.string.question_921_answer_2,
                Res.string.question_921_answer_3
            ),
            trueAnswer = Res.string.question_921_true_answer
        ),

        Question(
            question = Res.string.question_922,
            image = "question922_image.png",
            answers = listOf(
                Res.string.question_922_answer_1,
                Res.string.question_922_answer_2
            ),
            trueAnswer = Res.string.question_922_true_answer
        ),

        Question(
            question = Res.string.question_923,
            image = "question923_image.png",
            answers = listOf(
                Res.string.question_923_answer_1,
                Res.string.question_923_answer_2,
                Res.string.question_923_answer_3
            ),
            trueAnswer = Res.string.question_923_true_answer
        ),

        Question(
            question = Res.string.question_924,
            image = "question924_image.png",
            answers = listOf(
                Res.string.question_924_answer_1,
                Res.string.question_924_answer_2,
                Res.string.question_924_answer_3
            ),
            trueAnswer = Res.string.question_924_true_answer
        ),

        Question(
            question = Res.string.question_925,
            image = "question925_image.png",
            answers = listOf(
                Res.string.question_925_answer_1,
                Res.string.question_925_answer_2,
                Res.string.question_925_answer_3
            ),
            trueAnswer = Res.string.question_925_true_answer
        ),

        Question(
            question = Res.string.question_926,
            image = "question926_image.png",
            answers = listOf(
                Res.string.question_926_answer_1,
                Res.string.question_926_answer_2,
                Res.string.question_926_answer_3
            ),
            trueAnswer = Res.string.question_926_true_answer
        ),

        Question(
            question = Res.string.question_927,
            image = "question927_image.png",
            answers = listOf(
                Res.string.question_927_answer_1,
                Res.string.question_927_answer_2,
                Res.string.question_927_answer_3
            ),
            trueAnswer = Res.string.question_927_true_answer
        ),

        Question(
            question = Res.string.question_928,
            image = "question928_image.png",
            answers = listOf(
                Res.string.question_928_answer_1,
                Res.string.question_928_answer_2,
                Res.string.question_928_answer_3
            ),
            trueAnswer = Res.string.question_928_true_answer
        ),

        Question(
            question = Res.string.question_929,
            image = "question929_image.png",
            answers = listOf(
                Res.string.question_929_answer_1,
                Res.string.question_929_answer_2,
                Res.string.question_929_answer_3
            ),
            trueAnswer = Res.string.question_929_true_answer
        ),

        Question(
            question = Res.string.question_930,
            image = "question930_image.png",
            answers = listOf(
                Res.string.question_930_answer_1,
                Res.string.question_930_answer_2,
                Res.string.question_930_answer_3,
                Res.string.question_930_answer_4
            ),
            trueAnswer = Res.string.question_930_true_answer
        ),

        Question(
            question = Res.string.question_931,
            image = "question931_image.png",
            answers = listOf(
                Res.string.question_931_answer_1,
                Res.string.question_931_answer_2,
                Res.string.question_931_answer_3
            ),
            trueAnswer = Res.string.question_931_true_answer
        ),

        Question(
            question = Res.string.question_932,
            image = "question932_image.png",
            answers = listOf(
                Res.string.question_932_answer_1,
                Res.string.question_932_answer_2
            ),
            trueAnswer = Res.string.question_932_true_answer
        ),

        Question(
            question = Res.string.question_933,
            image = "question933_image.png",
            answers = listOf(
                Res.string.question_933_answer_1,
                Res.string.question_933_answer_2
            ),
            trueAnswer = Res.string.question_933_true_answer
        ),

        Question(
            question = Res.string.question_934,
            image = "question934_image.png",
            answers = listOf(
                Res.string.question_934_answer_1,
                Res.string.question_934_answer_2
            ),
            trueAnswer = Res.string.question_934_true_answer
        ),

        Question(
            question = Res.string.question_935,
            image = "question935_image.png",
            answers = listOf(
                Res.string.question_935_answer_1,
                Res.string.question_935_answer_2,
                Res.string.question_935_answer_3
            ),
            trueAnswer = Res.string.question_935_true_answer
        ),

        Question(
            question = Res.string.question_936,
            image = "question936_image.png",
            answers = listOf(
                Res.string.question_936_answer_1,
                Res.string.question_936_answer_2
            ),
            trueAnswer = Res.string.question_936_true_answer
        ),

        Question(
            question = Res.string.question_937,
            image = "question937_image.png",
            answers = listOf(
                Res.string.question_937_answer_1,
                Res.string.question_937_answer_2
            ),
            trueAnswer = Res.string.question_937_true_answer
        ),

        Question(
            question = Res.string.question_938,
            image = "question938_image.png",
            answers = listOf(
                Res.string.question_938_answer_1,
                Res.string.question_938_answer_2,
                Res.string.question_938_answer_3
            ),
            trueAnswer = Res.string.question_938_true_answer
        ),

        Question(
            question = Res.string.question_939,
            image = "question939_image.png",
            answers = listOf(
                Res.string.question_939_answer_1,
                Res.string.question_939_answer_2
            ),
            trueAnswer = Res.string.question_939_true_answer
        ),

        Question(
            question = Res.string.question_940,
            image = "question940_image.png",
            answers = listOf(
                Res.string.question_940_answer_1,
                Res.string.question_940_answer_2,
                Res.string.question_940_answer_3,
                Res.string.question_940_answer_4
            ),
            trueAnswer = Res.string.question_940_true_answer
        ),

        Question(
            question = Res.string.question_941,
            image = "question941_image.png",
            answers = listOf(
                Res.string.question_941_answer_1,
                Res.string.question_941_answer_2
            ),
            trueAnswer = Res.string.question_941_true_answer
        ),

        Question(
            question = Res.string.question_942,
            image = "question942_image.png",
            answers = listOf(
                Res.string.question_942_answer_1,
                Res.string.question_942_answer_2
            ),
            trueAnswer = Res.string.question_942_true_answer
        ),

        Question(
            question = Res.string.question_943,
            image = "question943_image.png",
            answers = listOf(
                Res.string.question_943_answer_1,
                Res.string.question_943_answer_2,
                Res.string.question_943_answer_3
            ),
            trueAnswer = Res.string.question_943_true_answer
        ),

        Question(
            question = Res.string.question_944,
            image = "question944_image.png",
            answers = listOf(
                Res.string.question_944_answer_1,
                Res.string.question_944_answer_2,
                Res.string.question_944_answer_3
            ),
            trueAnswer = Res.string.question_944_true_answer
        ),

        Question(
            question = Res.string.question_945,
            image = "question945_image.png",
            answers = listOf(
                Res.string.question_945_answer_1,
                Res.string.question_945_answer_2
            ),
            trueAnswer = Res.string.question_945_true_answer
        ),

        Question(
            question = Res.string.question_946,
            image = "question946_image.png",
            answers = listOf(
                Res.string.question_946_answer_1,
                Res.string.question_946_answer_2,
                Res.string.question_946_answer_3
            ),
            trueAnswer = Res.string.question_946_true_answer
        ),

        Question(
            question = Res.string.question_947,
            image = "question947_image.png",
            answers = listOf(
                Res.string.question_947_answer_1,
                Res.string.question_947_answer_2,
                Res.string.question_947_answer_3
            ),
            trueAnswer = Res.string.question_947_true_answer
        ),

        Question(
            question = Res.string.question_948,
            image = "question948_image.png",
            answers = listOf(
                Res.string.question_948_answer_1,
                Res.string.question_948_answer_2,
                Res.string.question_948_answer_3
            ),
            trueAnswer = Res.string.question_948_true_answer
        ),

        Question(
            question = Res.string.question_949,
            image = "question949_image.png",
            answers = listOf(
                Res.string.question_949_answer_1,
                Res.string.question_949_answer_2
            ),
            trueAnswer = Res.string.question_949_true_answer
        ),

        Question(
            question = Res.string.question_950,
            image = "question950_image.png",
            answers = listOf(
                Res.string.question_950_answer_1,
                Res.string.question_950_answer_2,
                Res.string.question_950_answer_3
            ),
            trueAnswer = Res.string.question_950_true_answer
        ),

        Question(
            question = Res.string.question_951,
            image = "question951_image.png",
            answers = listOf(
                Res.string.question_951_answer_1,
                Res.string.question_951_answer_2,
                Res.string.question_951_answer_3
            ),
            trueAnswer = Res.string.question_951_true_answer
        ),

        Question(
            question = Res.string.question_952,
            image = "question952_image.png",
            answers = listOf(
                Res.string.question_952_answer_1,
                Res.string.question_952_answer_2
            ),
            trueAnswer = Res.string.question_952_true_answer
        ),

        Question(
            question = Res.string.question_953,
            image = "question953_image.png",
            answers = listOf(
                Res.string.question_953_answer_1,
                Res.string.question_953_answer_2
            ),
            trueAnswer = Res.string.question_953_true_answer
        ),

        Question(
            question = Res.string.question_954,
            image = "question954_image.png",
            answers = listOf(
                Res.string.question_954_answer_1,
                Res.string.question_954_answer_2,
                Res.string.question_954_answer_3
            ),
            trueAnswer = Res.string.question_954_true_answer
        ),

        Question(
            question = Res.string.question_955,
            image = "question955_image.png",
            answers = listOf(
                Res.string.question_955_answer_1,
                Res.string.question_955_answer_2,
                Res.string.question_955_answer_3,
                Res.string.question_955_answer_4
            ),
            trueAnswer = Res.string.question_955_true_answer
        ),

        Question(
            question = Res.string.question_956,
            image = "question956_image.png",
            answers = listOf(
                Res.string.question_956_answer_1,
                Res.string.question_956_answer_2,
                Res.string.question_956_answer_3,
                Res.string.question_956_answer_4
            ),
            trueAnswer = Res.string.question_956_true_answer
        ),

        Question(
            question = Res.string.question_957,
            image = "question957_image.png",
            answers = listOf(
                Res.string.question_957_answer_1,
                Res.string.question_957_answer_2,
                Res.string.question_957_answer_3
            ),
            trueAnswer = Res.string.question_957_true_answer
        ),

        Question(
            question = Res.string.question_958,
            image = "question958_image.png",
            answers = listOf(
                Res.string.question_958_answer_1,
                Res.string.question_958_answer_2,
                Res.string.question_958_answer_3
            ),
            trueAnswer = Res.string.question_958_true_answer
        ),

        Question(
            question = Res.string.question_959,
            image = "question959_image.png",
            answers = listOf(
                Res.string.question_959_answer_1,
                Res.string.question_959_answer_2,
                Res.string.question_959_answer_3,
                Res.string.question_959_answer_4,
                Res.string.question_959_answer_5
            ),
            trueAnswer = Res.string.question_959_true_answer
        ),

        Question(
            question = Res.string.question_960,
            image = "question960_image.png",
            answers = listOf(
                Res.string.question_960_answer_1,
                Res.string.question_960_answer_2,
                Res.string.question_960_answer_3
            ),
            trueAnswer = Res.string.question_960_true_answer
        ),

        Question(
            question = Res.string.question_961,
            image = "question961_image.png",
            answers = listOf(
                Res.string.question_961_answer_1,
                Res.string.question_961_answer_2,
                Res.string.question_961_answer_3,
                Res.string.question_961_answer_4
            ),
            trueAnswer = Res.string.question_961_true_answer
        ),

        Question(
            question = Res.string.question_962,
            image = "question962_image.png",
            answers = listOf(
                Res.string.question_962_answer_1,
                Res.string.question_962_answer_2,
                Res.string.question_962_answer_3
            ),
            trueAnswer = Res.string.question_962_true_answer
        ),

        Question(
            question = Res.string.question_963,
            image = "question963_image.png",
            answers = listOf(
                Res.string.question_963_answer_1,
                Res.string.question_963_answer_2,
                Res.string.question_963_answer_3
            ),
            trueAnswer = Res.string.question_963_true_answer
        ),

        Question(
            question = Res.string.question_964,
            image = "question964_image.png",
            answers = listOf(
                Res.string.question_964_answer_1,
                Res.string.question_964_answer_2,
                Res.string.question_964_answer_3,
                Res.string.question_964_answer_4
            ),
            trueAnswer = Res.string.question_964_true_answer
        ),

        Question(
            question = Res.string.question_965,
            image = "question965_image.png",
            answers = listOf(
                Res.string.question_965_answer_1,
                Res.string.question_965_answer_2,
                Res.string.question_965_answer_3,
                Res.string.question_965_answer_4
            ),
            trueAnswer = Res.string.question_965_true_answer
        ),

        Question(
            question = Res.string.question_966,
            image = "question966_image.png",
            answers = listOf(
                Res.string.question_966_answer_1,
                Res.string.question_966_answer_2,
                Res.string.question_966_answer_3
            ),
            trueAnswer = Res.string.question_966_true_answer
        ),

        Question(
            question = Res.string.question_967,
            image = "question967_image.png",
            answers = listOf(
                Res.string.question_967_answer_1,
                Res.string.question_967_answer_2,
                Res.string.question_967_answer_3,
                Res.string.question_967_answer_4
            ),
            trueAnswer = Res.string.question_967_true_answer
        ),

        Question(
            question = Res.string.question_968,
            image = "question968_image.png",
            answers = listOf(
                Res.string.question_968_answer_1,
                Res.string.question_968_answer_2,
                Res.string.question_968_answer_3
            ),
            trueAnswer = Res.string.question_968_true_answer
        ),

        Question(
            question = Res.string.question_969,
            image = "question969_image.png",
            answers = listOf(
                Res.string.question_969_answer_1,
                Res.string.question_969_answer_2,
                Res.string.question_969_answer_3
            ),
            trueAnswer = Res.string.question_969_true_answer
        ),

        Question(
            question = Res.string.question_970,
            image = "question970_image.png",
            answers = listOf(
                Res.string.question_970_answer_1,
                Res.string.question_970_answer_2,
                Res.string.question_970_answer_3
            ),
            trueAnswer = Res.string.question_970_true_answer
        ),

        Question(
            question = Res.string.question_971,
            image = "question971_image.png",
            answers = listOf(
                Res.string.question_971_answer_1,
                Res.string.question_971_answer_2,
                Res.string.question_971_answer_3,
                Res.string.question_971_answer_4
            ),
            trueAnswer = Res.string.question_971_true_answer
        ),

        Question(
            question = Res.string.question_972,
            image = "question972_image.png",
            answers = listOf(
                Res.string.question_972_answer_1,
                Res.string.question_972_answer_2,
                Res.string.question_972_answer_3
            ),
            trueAnswer = Res.string.question_972_true_answer
        ),

        Question(
            question = Res.string.question_973,
            image = "question973_image.png",
            answers = listOf(
                Res.string.question_973_answer_1,
                Res.string.question_973_answer_2,
                Res.string.question_973_answer_3
            ),
            trueAnswer = Res.string.question_973_true_answer
        ),

        Question(
            question = Res.string.question_974,
            image = "question974_image.png",
            answers = listOf(
                Res.string.question_974_answer_1,
                Res.string.question_974_answer_2,
                Res.string.question_974_answer_3
            ),
            trueAnswer = Res.string.question_974_true_answer
        ),

        Question(
            question = Res.string.question_975,
            image = "question975_image.png",
            answers = listOf(
                Res.string.question_975_answer_1,
                Res.string.question_975_answer_2,
                Res.string.question_975_answer_3
            ),
            trueAnswer = Res.string.question_975_true_answer
        ),

        Question(
            question = Res.string.question_976,
            image = "question976_image.png",
            answers = listOf(
                Res.string.question_976_answer_1,
                Res.string.question_976_answer_2,
                Res.string.question_976_answer_3
            ),
            trueAnswer = Res.string.question_976_true_answer
        ),

        Question(
            question = Res.string.question_977,
            image = "question977_image.png",
            answers = listOf(
                Res.string.question_977_answer_1,
                Res.string.question_977_answer_2
            ),
            trueAnswer = Res.string.question_977_true_answer
        ),

        Question(
            question = Res.string.question_978,
            image = "question978_image.png",
            answers = listOf(
                Res.string.question_978_answer_1,
                Res.string.question_978_answer_2,
                Res.string.question_978_answer_3,
                Res.string.question_978_answer_4
            ),
            trueAnswer = Res.string.question_978_true_answer
        ),

        Question(
            question = Res.string.question_979,
            image = "question979_image.png",
            answers = listOf(
                Res.string.question_979_answer_1,
                Res.string.question_979_answer_2
            ),
            trueAnswer = Res.string.question_979_true_answer
        ),

        Question(
            question = Res.string.question_980,
            image = "question980_image.png",
            answers = listOf(
                Res.string.question_980_answer_1,
                Res.string.question_980_answer_2
            ),
            trueAnswer = Res.string.question_980_true_answer
        ),

        Question(
            question = Res.string.question_981,
            image = "question981_image.png",
            answers = listOf(
                Res.string.question_981_answer_1,
                Res.string.question_981_answer_2
            ),
            trueAnswer = Res.string.question_981_true_answer
        ),

        Question(
            question = Res.string.question_982,
            image = "question982_image.png",
            answers = listOf(
                Res.string.question_982_answer_1,
                Res.string.question_982_answer_2
            ),
            trueAnswer = Res.string.question_982_true_answer
        ),

        Question(
            question = Res.string.question_983,
            image = "question983_image.png",
            answers = listOf(
                Res.string.question_983_answer_1,
                Res.string.question_983_answer_2,
                Res.string.question_983_answer_3,
                Res.string.question_983_answer_4
            ),
            trueAnswer = Res.string.question_983_true_answer
        ),

        Question(
            question = Res.string.question_984,
            image = "question984_image.png",
            answers = listOf(
                Res.string.question_984_answer_1,
                Res.string.question_984_answer_2,
                Res.string.question_984_answer_3,
                Res.string.question_984_answer_4
            ),
            trueAnswer = Res.string.question_984_true_answer
        ),

        Question(
            question = Res.string.question_985,
            image = "question985_image.png",
            answers = listOf(
                Res.string.question_985_answer_1,
                Res.string.question_985_answer_2,
                Res.string.question_985_answer_3,
                Res.string.question_985_answer_4
            ),
            trueAnswer = Res.string.question_985_true_answer
        ),

        Question(
            question = Res.string.question_986,
            image = "question986_image.png",
            answers = listOf(
                Res.string.question_986_answer_1,
                Res.string.question_986_answer_2
            ),
            trueAnswer = Res.string.question_986_true_answer
        ),

        Question(
            question = Res.string.question_987,
            image = "question987_image.png",
            answers = listOf(
                Res.string.question_987_answer_1,
                Res.string.question_987_answer_2,
                Res.string.question_987_answer_3
            ),
            trueAnswer = Res.string.question_987_true_answer
        ),

        Question(
            question = Res.string.question_988,
            image = "question988_image.png",
            answers = listOf(
                Res.string.question_988_answer_1,
                Res.string.question_988_answer_2,
                Res.string.question_988_answer_3
            ),
            trueAnswer = Res.string.question_988_true_answer
        ),

        Question(
            question = Res.string.question_989,
            image = "question989_image.png",
            answers = listOf(
                Res.string.question_989_answer_1,
                Res.string.question_989_answer_2,
                Res.string.question_989_answer_3
            ),
            trueAnswer = Res.string.question_989_true_answer
        ),

        Question(
            question = Res.string.question_990,
            image = "question990_image.png",
            answers = listOf(
                Res.string.question_990_answer_1,
                Res.string.question_990_answer_2
            ),
            trueAnswer = Res.string.question_990_true_answer
        ),

        Question(
            question = Res.string.question_991,
            image = "question991_image.png",
            answers = listOf(
                Res.string.question_991_answer_1,
                Res.string.question_991_answer_2,
                Res.string.question_991_answer_3
            ),
            trueAnswer = Res.string.question_991_true_answer
        ),

        Question(
            question = Res.string.question_992,
            image = "question992_image.png",
            answers = listOf(
                Res.string.question_992_answer_1,
                Res.string.question_992_answer_2,
                Res.string.question_992_answer_3
            ),
            trueAnswer = Res.string.question_992_true_answer
        ),

        Question(
            question = Res.string.question_993,
            image = "question993_image.png",
            answers = listOf(
                Res.string.question_993_answer_1,
                Res.string.question_993_answer_2,
                Res.string.question_993_answer_3
            ),
            trueAnswer = Res.string.question_993_true_answer
        ),

        Question(
            question = Res.string.question_994,
            image = "question994_image.png",
            answers = listOf(
                Res.string.question_994_answer_1,
                Res.string.question_994_answer_2
            ),
            trueAnswer = Res.string.question_994_true_answer
        ),

        Question(
            question = Res.string.question_995,
            image = "question995_image.png",
            answers = listOf(
                Res.string.question_995_answer_1,
                Res.string.question_995_answer_2,
                Res.string.question_995_answer_3
            ),
            trueAnswer = Res.string.question_995_true_answer
        ),

        Question(
            question = Res.string.question_996,
            image = "question996_image.png",
            answers = listOf(
                Res.string.question_996_answer_1,
                Res.string.question_996_answer_2
            ),
            trueAnswer = Res.string.question_996_true_answer
        ),

        Question(
            question = Res.string.question_997,
            image = "question997_image.png",
            answers = listOf(
                Res.string.question_997_answer_1,
                Res.string.question_997_answer_2
            ),
            trueAnswer = Res.string.question_997_true_answer
        ),

        Question(
            question = Res.string.question_998,
            image = "question998_image.png",
            answers = listOf(
                Res.string.question_998_answer_1,
                Res.string.question_998_answer_2,
                Res.string.question_998_answer_3,
                Res.string.question_998_answer_4
            ),
            trueAnswer = Res.string.question_998_true_answer
        ),

        Question(
            question = Res.string.question_999,
            image = "question999_image.png",
            answers = listOf(
                Res.string.question_999_answer_1,
                Res.string.question_999_answer_2
            ),
            trueAnswer = Res.string.question_999_true_answer
        ),

        Question(
            question = Res.string.question_1000,
            image = "question1000_image.png",
            answers = listOf(
                Res.string.question_1000_answer_1,
                Res.string.question_1000_answer_2,
                Res.string.question_1000_answer_3
            ),
            trueAnswer = Res.string.question_1000_true_answer
        ),

        Question(
            question = Res.string.question_1001,
            image = "question1001_image.png",
            answers = listOf(
                Res.string.question_1001_answer_1,
                Res.string.question_1001_answer_2
            ),
            trueAnswer = Res.string.question_1001_true_answer
        ),

        Question(
            question = Res.string.question_1002,
            image = "question1002_image.png",
            answers = listOf(
                Res.string.question_1002_answer_1,
                Res.string.question_1002_answer_2,
                Res.string.question_1002_answer_3
            ),
            trueAnswer = Res.string.question_1002_true_answer
        ),

        Question(
            question = Res.string.question_1003,
            image = "question1003_image.png",
            answers = listOf(
                Res.string.question_1003_answer_1,
                Res.string.question_1003_answer_2
            ),
            trueAnswer = Res.string.question_1003_true_answer
        ),

        Question(
            question = Res.string.question_1004,
            image = "question1004_image.png",
            answers = listOf(
                Res.string.question_1004_answer_1,
                Res.string.question_1004_answer_2,
                Res.string.question_1004_answer_3
            ),
            trueAnswer = Res.string.question_1004_true_answer
        ),

        Question(
            question = Res.string.question_1005,
            image = "question1005_image.png",
            answers = listOf(
                Res.string.question_1005_answer_1,
                Res.string.question_1005_answer_2,
                Res.string.question_1005_answer_3
            ),
            trueAnswer = Res.string.question_1005_true_answer
        ),

        Question(
            question = Res.string.question_1006,
            image = "question1006_image.png",
            answers = listOf(
                Res.string.question_1006_answer_1,
                Res.string.question_1006_answer_2,
                Res.string.question_1006_answer_3
            ),
            trueAnswer = Res.string.question_1006_true_answer
        ),

        Question(
            question = Res.string.question_1007,
            image = "question1007_image.png",
            answers = listOf(
                Res.string.question_1007_answer_1,
                Res.string.question_1007_answer_2,
                Res.string.question_1007_answer_3
            ),
            trueAnswer = Res.string.question_1007_true_answer
        ),

        Question(
            question = Res.string.question_1008,
            image = "question1008_image.png",
            answers = listOf(
                Res.string.question_1008_answer_1,
                Res.string.question_1008_answer_2,
                Res.string.question_1008_answer_3
            ),
            trueAnswer = Res.string.question_1008_true_answer
        ),

        Question(
            question = Res.string.question_1009,
            image = "question1009_image.png",
            answers = listOf(
                Res.string.question_1009_answer_1,
                Res.string.question_1009_answer_2
            ),
            trueAnswer = Res.string.question_1009_true_answer
        ),

        Question(
            question = Res.string.question_1010,
            image = "question1010_image.png",
            answers = listOf(
                Res.string.question_1010_answer_1,
                Res.string.question_1010_answer_2,
                Res.string.question_1010_answer_3
            ),
            trueAnswer = Res.string.question_1010_true_answer
        ),

        Question(
            question = Res.string.question_1011,
            image = "question1011_image.png",
            answers = listOf(
                Res.string.question_1011_answer_1,
                Res.string.question_1011_answer_2,
                Res.string.question_1011_answer_3
            ),
            trueAnswer = Res.string.question_1011_true_answer
        ),

        Question(
            question = Res.string.question_1012,
            image = "question1012_image.png",
            answers = listOf(
                Res.string.question_1012_answer_1,
                Res.string.question_1012_answer_2,
                Res.string.question_1012_answer_3
            ),
            trueAnswer = Res.string.question_1012_true_answer
        ),

        Question(
            question = Res.string.question_1013,
            image = "question1013_image.png",
            answers = listOf(
                Res.string.question_1013_answer_1,
                Res.string.question_1013_answer_2
            ),
            trueAnswer = Res.string.question_1013_true_answer
        ),

        Question(
            question = Res.string.question_1014,
            image = "question1014_image.png",
            answers = listOf(
                Res.string.question_1014_answer_1,
                Res.string.question_1014_answer_2,
                Res.string.question_1014_answer_3
            ),
            trueAnswer = Res.string.question_1014_true_answer
        ),

        Question(
            question = Res.string.question_1015,
            image = "question1015_image.png",
            answers = listOf(
                Res.string.question_1015_answer_1,
                Res.string.question_1015_answer_2,
                Res.string.question_1015_answer_3
            ),
            trueAnswer = Res.string.question_1015_true_answer
        ),

        Question(
            question = Res.string.question_1016,
            image = "question1016_image.png",
            answers = listOf(
                Res.string.question_1016_answer_1,
                Res.string.question_1016_answer_2
            ),
            trueAnswer = Res.string.question_1016_true_answer
        ),

        Question(
            question = Res.string.question_1017,
            image = "question1017_image.png",
            answers = listOf(
                Res.string.question_1017_answer_1,
                Res.string.question_1017_answer_2,
                Res.string.question_1017_answer_3
            ),
            trueAnswer = Res.string.question_1017_true_answer
        ),

        Question(
            question = Res.string.question_1018,
            image = "question1018_image.png",
            answers = listOf(
                Res.string.question_1018_answer_1,
                Res.string.question_1018_answer_2,
                Res.string.question_1018_answer_3
            ),
            trueAnswer = Res.string.question_1018_true_answer
        ),

        Question(
            question = Res.string.question_1019,
            image = "question1019_image.png",
            answers = listOf(
                Res.string.question_1019_answer_1,
                Res.string.question_1019_answer_2,
                Res.string.question_1019_answer_3
            ),
            trueAnswer = Res.string.question_1019_true_answer
        ),

        Question(
            question = Res.string.question_1020,
            image = "question1020_image.png",
            answers = listOf(
                Res.string.question_1020_answer_1,
                Res.string.question_1020_answer_2,
                Res.string.question_1020_answer_3
            ),
            trueAnswer = Res.string.question_1020_true_answer
        ),

        Question(
            question = Res.string.question_1021,
            image = "question1021_image.png",
            answers = listOf(
                Res.string.question_1021_answer_1,
                Res.string.question_1021_answer_2,
                Res.string.question_1021_answer_3
            ),
            trueAnswer = Res.string.question_1021_true_answer
        ),

        Question(
            question = Res.string.question_1022,
            image = "question1022_image.png",
            answers = listOf(
                Res.string.question_1022_answer_1,
                Res.string.question_1022_answer_2,
                Res.string.question_1022_answer_3
            ),
            trueAnswer = Res.string.question_1022_true_answer
        ),

        Question(
            question = Res.string.question_1023,
            image = "question1023_image.png",
            answers = listOf(
                Res.string.question_1023_answer_1,
                Res.string.question_1023_answer_2,
                Res.string.question_1023_answer_3
            ),
            trueAnswer = Res.string.question_1023_true_answer
        ),

        Question(
            question = Res.string.question_1024,
            image = "question1024_image.png",
            answers = listOf(
                Res.string.question_1024_answer_1,
                Res.string.question_1024_answer_2
            ),
            trueAnswer = Res.string.question_1024_true_answer
        ),

        Question(
            question = Res.string.question_1025,
            image = "question1025_image.png",
            answers = listOf(
                Res.string.question_1025_answer_1,
                Res.string.question_1025_answer_2,
                Res.string.question_1025_answer_3
            ),
            trueAnswer = Res.string.question_1025_true_answer
        ),

        Question(
            question = Res.string.question_1026,
            image = "question1026_image.png",
            answers = listOf(
                Res.string.question_1026_answer_1,
                Res.string.question_1026_answer_2,
                Res.string.question_1026_answer_3
            ),
            trueAnswer = Res.string.question_1026_true_answer
        ),

        Question(
            question = Res.string.question_1027,
            image = "question1027_image.png",
            answers = listOf(
                Res.string.question_1027_answer_1,
                Res.string.question_1027_answer_2,
                Res.string.question_1027_answer_3
            ),
            trueAnswer = Res.string.question_1027_true_answer
        ),

        Question(
            question = Res.string.question_1028,
            image = "question1028_image.png",
            answers = listOf(
                Res.string.question_1028_answer_1,
                Res.string.question_1028_answer_2,
                Res.string.question_1028_answer_3
            ),
            trueAnswer = Res.string.question_1028_true_answer
        ),

        Question(
            question = Res.string.question_1029,
            image = "question1029_image.png",
            answers = listOf(
                Res.string.question_1029_answer_1,
                Res.string.question_1029_answer_2,
                Res.string.question_1029_answer_3
            ),
            trueAnswer = Res.string.question_1029_true_answer
        ),

        Question(
            question = Res.string.question_1030,
            image = "question1030_image.png",
            answers = listOf(
                Res.string.question_1030_answer_1,
                Res.string.question_1030_answer_2
            ),
            trueAnswer = Res.string.question_1030_true_answer
        ),

        Question(
            question = Res.string.question_1031,
            image = "question1031_image.png",
            answers = listOf(
                Res.string.question_1031_answer_1,
                Res.string.question_1031_answer_2,
                Res.string.question_1031_answer_3
            ),
            trueAnswer = Res.string.question_1031_true_answer
        ),

        Question(
            question = Res.string.question_1032,
            image = "question1032_image.png",
            answers = listOf(
                Res.string.question_1032_answer_1,
                Res.string.question_1032_answer_2
            ),
            trueAnswer = Res.string.question_1032_true_answer
        ),

        Question(
            question = Res.string.question_1033,
            image = "question1033_image.png",
            answers = listOf(
                Res.string.question_1033_answer_1,
                Res.string.question_1033_answer_2,
                Res.string.question_1033_answer_3
            ),
            trueAnswer = Res.string.question_1033_true_answer
        ),

        Question(
            question = Res.string.question_1034,
            image = "question1034_image.png",
            answers = listOf(
                Res.string.question_1034_answer_1,
                Res.string.question_1034_answer_2,
                Res.string.question_1034_answer_3
            ),
            trueAnswer = Res.string.question_1034_true_answer
        ),

        Question(
            question = Res.string.question_1035,
            image = "question1035_image.png",
            answers = listOf(
                Res.string.question_1035_answer_1,
                Res.string.question_1035_answer_2
            ),
            trueAnswer = Res.string.question_1035_true_answer
        ),

        Question(
            question = Res.string.question_1036,
            image = "question1036_image.png",
            answers = listOf(
                Res.string.question_1036_answer_1,
                Res.string.question_1036_answer_2
            ),
            trueAnswer = Res.string.question_1036_true_answer
        ),

        Question(
            question = Res.string.question_1037,
            image = "question1037_image.png",
            answers = listOf(
                Res.string.question_1037_answer_1,
                Res.string.question_1037_answer_2
            ),
            trueAnswer = Res.string.question_1037_true_answer
        ),

        Question(
            question = Res.string.question_1038,
            image = "question1038_image.png",
            answers = listOf(
                Res.string.question_1038_answer_1,
                Res.string.question_1038_answer_2
            ),
            trueAnswer = Res.string.question_1038_true_answer
        ),

        Question(
            question = Res.string.question_1039,
            image = "question1039_image.png",
            answers = listOf(
                Res.string.question_1039_answer_1,
                Res.string.question_1039_answer_2,
                Res.string.question_1039_answer_3
            ),
            trueAnswer = Res.string.question_1039_true_answer
        ),

        Question(
            question = Res.string.question_1040,
            image = "question1040_image.png",
            answers = listOf(
                Res.string.question_1040_answer_1,
                Res.string.question_1040_answer_2,
                Res.string.question_1040_answer_3
            ),
            trueAnswer = Res.string.question_1040_true_answer
        ),

        Question(
            question = Res.string.question_1041,
            image = "question1041_image.png",
            answers = listOf(
                Res.string.question_1041_answer_1,
                Res.string.question_1041_answer_2
            ),
            trueAnswer = Res.string.question_1041_true_answer
        ),

        Question(
            question = Res.string.question_1042,
            image = "question1042_image.png",
            answers = listOf(
                Res.string.question_1042_answer_1,
                Res.string.question_1042_answer_2,
                Res.string.question_1042_answer_3
            ),
            trueAnswer = Res.string.question_1042_true_answer
        ),

        Question(
            question = Res.string.question_1043,
            image = "question1043_image.png",
            answers = listOf(
                Res.string.question_1043_answer_1,
                Res.string.question_1043_answer_2,
                Res.string.question_1043_answer_3
            ),
            trueAnswer = Res.string.question_1043_true_answer
        )
    )
}