package com.drive.license.test.models

enum class QuestionCategory {
    TRAFFIC_SIGNS_AND_MARKINGS,
    LANE_USAGE_AND_POSITIONING,
    MANEUVERS_AND_TURNS,
    RIGHT_OF_WAY_AND_PRIORITY,
    PROHIBITED_ACTIONS,
    SPECIAL_VEHICLES_AND_SITUATIONS,
    INTERSECTIONS_AND_CROSSINGS,
    ROAD_CONDITIONS_AND_VISIBILITY,
    VEHICLE_TYPES_AND_CATEGORIES,
    GENERAL_TRAFFIC_RULES
} 