package com.drive.license.test.models

import drivelicensetest.composeapp.generated.resources.Res
import drivelicensetest.composeapp.generated.resources.question_474
import drivelicensetest.composeapp.generated.resources.question_474_answer_1
import drivelicensetest.composeapp.generated.resources.question_474_answer_2
import drivelicensetest.composeapp.generated.resources.question_474_answer_3
import drivelicensetest.composeapp.generated.resources.question_474_true_answer
import drivelicensetest.composeapp.generated.resources.question_475
import drivelicensetest.composeapp.generated.resources.question_475_answer_1
import drivelicensetest.composeapp.generated.resources.question_475_answer_2
import drivelicensetest.composeapp.generated.resources.question_475_answer_3
import drivelicensetest.composeapp.generated.resources.question_475_answer_4
import drivelicensetest.composeapp.generated.resources.question_475_true_answer
import drivelicensetest.composeapp.generated.resources.question_476
import drivelicensetest.composeapp.generated.resources.question_476_answer_1
import drivelicensetest.composeapp.generated.resources.question_476_answer_2
import drivelicensetest.composeapp.generated.resources.question_476_answer_3
import drivelicensetest.composeapp.generated.resources.question_476_true_answer
import drivelicensetest.composeapp.generated.resources.question_477
import drivelicensetest.composeapp.generated.resources.question_477_answer_1
import drivelicensetest.composeapp.generated.resources.question_477_answer_2
import drivelicensetest.composeapp.generated.resources.question_477_true_answer
import drivelicensetest.composeapp.generated.resources.question_478
import drivelicensetest.composeapp.generated.resources.question_478_answer_1
import drivelicensetest.composeapp.generated.resources.question_478_answer_2
import drivelicensetest.composeapp.generated.resources.question_478_answer_3
import drivelicensetest.composeapp.generated.resources.question_478_true_answer
import drivelicensetest.composeapp.generated.resources.question_479
import drivelicensetest.composeapp.generated.resources.question_479_answer_1
import drivelicensetest.composeapp.generated.resources.question_479_answer_2
import drivelicensetest.composeapp.generated.resources.question_479_answer_3
import drivelicensetest.composeapp.generated.resources.question_479_true_answer
import drivelicensetest.composeapp.generated.resources.question_480
import drivelicensetest.composeapp.generated.resources.question_480_answer_1
import drivelicensetest.composeapp.generated.resources.question_480_answer_2
import drivelicensetest.composeapp.generated.resources.question_480_answer_3
import drivelicensetest.composeapp.generated.resources.question_480_true_answer
import drivelicensetest.composeapp.generated.resources.question_481
import drivelicensetest.composeapp.generated.resources.question_481_answer_1
import drivelicensetest.composeapp.generated.resources.question_481_answer_2
import drivelicensetest.composeapp.generated.resources.question_481_answer_3
import drivelicensetest.composeapp.generated.resources.question_481_true_answer
import drivelicensetest.composeapp.generated.resources.question_482
import drivelicensetest.composeapp.generated.resources.question_482_answer_1
import drivelicensetest.composeapp.generated.resources.question_482_answer_2
import drivelicensetest.composeapp.generated.resources.question_482_answer_3
import drivelicensetest.composeapp.generated.resources.question_482_true_answer
import drivelicensetest.composeapp.generated.resources.question_483
import drivelicensetest.composeapp.generated.resources.question_483_answer_1
import drivelicensetest.composeapp.generated.resources.question_483_answer_2
import drivelicensetest.composeapp.generated.resources.question_483_answer_3
import drivelicensetest.composeapp.generated.resources.question_483_true_answer
import drivelicensetest.composeapp.generated.resources.question_484
import drivelicensetest.composeapp.generated.resources.question_484_answer_1
import drivelicensetest.composeapp.generated.resources.question_484_answer_2
import drivelicensetest.composeapp.generated.resources.question_484_answer_3
import drivelicensetest.composeapp.generated.resources.question_484_answer_4
import drivelicensetest.composeapp.generated.resources.question_484_true_answer
import drivelicensetest.composeapp.generated.resources.question_485
import drivelicensetest.composeapp.generated.resources.question_485_answer_1
import drivelicensetest.composeapp.generated.resources.question_485_answer_2
import drivelicensetest.composeapp.generated.resources.question_485_true_answer
import drivelicensetest.composeapp.generated.resources.question_486
import drivelicensetest.composeapp.generated.resources.question_486_answer_1
import drivelicensetest.composeapp.generated.resources.question_486_answer_2
import drivelicensetest.composeapp.generated.resources.question_486_answer_3
import drivelicensetest.composeapp.generated.resources.question_486_answer_4
import drivelicensetest.composeapp.generated.resources.question_486_true_answer
import drivelicensetest.composeapp.generated.resources.question_487
import drivelicensetest.composeapp.generated.resources.question_487_answer_1
import drivelicensetest.composeapp.generated.resources.question_487_answer_2
import drivelicensetest.composeapp.generated.resources.question_487_answer_3
import drivelicensetest.composeapp.generated.resources.question_487_true_answer
import drivelicensetest.composeapp.generated.resources.question_488
import drivelicensetest.composeapp.generated.resources.question_488_answer_1
import drivelicensetest.composeapp.generated.resources.question_488_answer_2
import drivelicensetest.composeapp.generated.resources.question_488_answer_3
import drivelicensetest.composeapp.generated.resources.question_488_true_answer
import drivelicensetest.composeapp.generated.resources.question_489
import drivelicensetest.composeapp.generated.resources.question_489_answer_1
import drivelicensetest.composeapp.generated.resources.question_489_answer_2
import drivelicensetest.composeapp.generated.resources.question_489_answer_3
import drivelicensetest.composeapp.generated.resources.question_489_true_answer
import drivelicensetest.composeapp.generated.resources.question_490
import drivelicensetest.composeapp.generated.resources.question_490_answer_1
import drivelicensetest.composeapp.generated.resources.question_490_answer_2
import drivelicensetest.composeapp.generated.resources.question_490_answer_3
import drivelicensetest.composeapp.generated.resources.question_490_true_answer
import drivelicensetest.composeapp.generated.resources.question_491
import drivelicensetest.composeapp.generated.resources.question_491_answer_1
import drivelicensetest.composeapp.generated.resources.question_491_answer_2
import drivelicensetest.composeapp.generated.resources.question_491_answer_3
import drivelicensetest.composeapp.generated.resources.question_491_true_answer
import drivelicensetest.composeapp.generated.resources.question_492
import drivelicensetest.composeapp.generated.resources.question_492_answer_1
import drivelicensetest.composeapp.generated.resources.question_492_answer_2
import drivelicensetest.composeapp.generated.resources.question_492_true_answer
import drivelicensetest.composeapp.generated.resources.question_493
import drivelicensetest.composeapp.generated.resources.question_493_answer_1
import drivelicensetest.composeapp.generated.resources.question_493_answer_2
import drivelicensetest.composeapp.generated.resources.question_493_answer_3
import drivelicensetest.composeapp.generated.resources.question_493_true_answer
import drivelicensetest.composeapp.generated.resources.question_494
import drivelicensetest.composeapp.generated.resources.question_494_answer_1
import drivelicensetest.composeapp.generated.resources.question_494_answer_2
import drivelicensetest.composeapp.generated.resources.question_494_answer_3
import drivelicensetest.composeapp.generated.resources.question_494_true_answer
import drivelicensetest.composeapp.generated.resources.question_495
import drivelicensetest.composeapp.generated.resources.question_495_answer_1
import drivelicensetest.composeapp.generated.resources.question_495_answer_2
import drivelicensetest.composeapp.generated.resources.question_495_answer_3
import drivelicensetest.composeapp.generated.resources.question_495_answer_4
import drivelicensetest.composeapp.generated.resources.question_495_true_answer
import drivelicensetest.composeapp.generated.resources.question_496
import drivelicensetest.composeapp.generated.resources.question_496_answer_1
import drivelicensetest.composeapp.generated.resources.question_496_answer_2
import drivelicensetest.composeapp.generated.resources.question_496_true_answer
import drivelicensetest.composeapp.generated.resources.question_497
import drivelicensetest.composeapp.generated.resources.question_497_answer_1
import drivelicensetest.composeapp.generated.resources.question_497_answer_2
import drivelicensetest.composeapp.generated.resources.question_497_true_answer
import drivelicensetest.composeapp.generated.resources.question_498
import drivelicensetest.composeapp.generated.resources.question_498_answer_1
import drivelicensetest.composeapp.generated.resources.question_498_answer_2
import drivelicensetest.composeapp.generated.resources.question_498_answer_3
import drivelicensetest.composeapp.generated.resources.question_498_answer_4
import drivelicensetest.composeapp.generated.resources.question_498_true_answer
import drivelicensetest.composeapp.generated.resources.question_499
import drivelicensetest.composeapp.generated.resources.question_499_answer_1
import drivelicensetest.composeapp.generated.resources.question_499_answer_2
import drivelicensetest.composeapp.generated.resources.question_499_answer_3
import drivelicensetest.composeapp.generated.resources.question_499_true_answer
import drivelicensetest.composeapp.generated.resources.question_500
import drivelicensetest.composeapp.generated.resources.question_500_answer_1
import drivelicensetest.composeapp.generated.resources.question_500_answer_2
import drivelicensetest.composeapp.generated.resources.question_500_answer_3
import drivelicensetest.composeapp.generated.resources.question_500_true_answer
import drivelicensetest.composeapp.generated.resources.question_501
import drivelicensetest.composeapp.generated.resources.question_501_answer_1
import drivelicensetest.composeapp.generated.resources.question_501_answer_2
import drivelicensetest.composeapp.generated.resources.question_501_answer_3
import drivelicensetest.composeapp.generated.resources.question_501_true_answer
import drivelicensetest.composeapp.generated.resources.question_502
import drivelicensetest.composeapp.generated.resources.question_502_answer_1
import drivelicensetest.composeapp.generated.resources.question_502_answer_2
import drivelicensetest.composeapp.generated.resources.question_502_true_answer
import drivelicensetest.composeapp.generated.resources.question_503
import drivelicensetest.composeapp.generated.resources.question_503_answer_1
import drivelicensetest.composeapp.generated.resources.question_503_answer_2
import drivelicensetest.composeapp.generated.resources.question_503_answer_3
import drivelicensetest.composeapp.generated.resources.question_503_true_answer
import drivelicensetest.composeapp.generated.resources.question_504
import drivelicensetest.composeapp.generated.resources.question_504_answer_1
import drivelicensetest.composeapp.generated.resources.question_504_answer_2
import drivelicensetest.composeapp.generated.resources.question_504_answer_3
import drivelicensetest.composeapp.generated.resources.question_504_true_answer
import drivelicensetest.composeapp.generated.resources.question_505
import drivelicensetest.composeapp.generated.resources.question_505_answer_1
import drivelicensetest.composeapp.generated.resources.question_505_answer_2
import drivelicensetest.composeapp.generated.resources.question_505_true_answer
import drivelicensetest.composeapp.generated.resources.question_506
import drivelicensetest.composeapp.generated.resources.question_506_answer_1
import drivelicensetest.composeapp.generated.resources.question_506_answer_2
import drivelicensetest.composeapp.generated.resources.question_506_answer_3
import drivelicensetest.composeapp.generated.resources.question_506_answer_4
import drivelicensetest.composeapp.generated.resources.question_506_true_answer
import drivelicensetest.composeapp.generated.resources.question_507
import drivelicensetest.composeapp.generated.resources.question_507_answer_1
import drivelicensetest.composeapp.generated.resources.question_507_answer_2
import drivelicensetest.composeapp.generated.resources.question_507_true_answer
import drivelicensetest.composeapp.generated.resources.question_508
import drivelicensetest.composeapp.generated.resources.question_508_answer_1
import drivelicensetest.composeapp.generated.resources.question_508_answer_2
import drivelicensetest.composeapp.generated.resources.question_508_answer_3
import drivelicensetest.composeapp.generated.resources.question_508_true_answer
import drivelicensetest.composeapp.generated.resources.question_509
import drivelicensetest.composeapp.generated.resources.question_509_answer_1
import drivelicensetest.composeapp.generated.resources.question_509_answer_2
import drivelicensetest.composeapp.generated.resources.question_509_true_answer
import drivelicensetest.composeapp.generated.resources.question_510
import drivelicensetest.composeapp.generated.resources.question_510_answer_1
import drivelicensetest.composeapp.generated.resources.question_510_answer_2
import drivelicensetest.composeapp.generated.resources.question_510_true_answer
import drivelicensetest.composeapp.generated.resources.question_511
import drivelicensetest.composeapp.generated.resources.question_511_answer_1
import drivelicensetest.composeapp.generated.resources.question_511_answer_2
import drivelicensetest.composeapp.generated.resources.question_511_true_answer
import drivelicensetest.composeapp.generated.resources.question_512
import drivelicensetest.composeapp.generated.resources.question_512_answer_1
import drivelicensetest.composeapp.generated.resources.question_512_answer_2
import drivelicensetest.composeapp.generated.resources.question_512_answer_3
import drivelicensetest.composeapp.generated.resources.question_512_true_answer
import drivelicensetest.composeapp.generated.resources.question_513
import drivelicensetest.composeapp.generated.resources.question_513_answer_1
import drivelicensetest.composeapp.generated.resources.question_513_answer_2
import drivelicensetest.composeapp.generated.resources.question_513_true_answer
import drivelicensetest.composeapp.generated.resources.question_514
import drivelicensetest.composeapp.generated.resources.question_514_answer_1
import drivelicensetest.composeapp.generated.resources.question_514_answer_2
import drivelicensetest.composeapp.generated.resources.question_514_true_answer
import drivelicensetest.composeapp.generated.resources.question_515
import drivelicensetest.composeapp.generated.resources.question_515_answer_1
import drivelicensetest.composeapp.generated.resources.question_515_answer_2
import drivelicensetest.composeapp.generated.resources.question_515_answer_3
import drivelicensetest.composeapp.generated.resources.question_515_true_answer
import drivelicensetest.composeapp.generated.resources.question_516
import drivelicensetest.composeapp.generated.resources.question_516_answer_1
import drivelicensetest.composeapp.generated.resources.question_516_answer_2
import drivelicensetest.composeapp.generated.resources.question_516_true_answer
import drivelicensetest.composeapp.generated.resources.question_517
import drivelicensetest.composeapp.generated.resources.question_517_answer_1
import drivelicensetest.composeapp.generated.resources.question_517_answer_2
import drivelicensetest.composeapp.generated.resources.question_517_answer_3
import drivelicensetest.composeapp.generated.resources.question_517_true_answer
import drivelicensetest.composeapp.generated.resources.question_518
import drivelicensetest.composeapp.generated.resources.question_518_answer_1
import drivelicensetest.composeapp.generated.resources.question_518_answer_2
import drivelicensetest.composeapp.generated.resources.question_518_true_answer
import drivelicensetest.composeapp.generated.resources.question_519
import drivelicensetest.composeapp.generated.resources.question_519_answer_1
import drivelicensetest.composeapp.generated.resources.question_519_answer_2
import drivelicensetest.composeapp.generated.resources.question_519_answer_3
import drivelicensetest.composeapp.generated.resources.question_519_true_answer
import drivelicensetest.composeapp.generated.resources.question_520
import drivelicensetest.composeapp.generated.resources.question_520_answer_1
import drivelicensetest.composeapp.generated.resources.question_520_answer_2
import drivelicensetest.composeapp.generated.resources.question_520_answer_3
import drivelicensetest.composeapp.generated.resources.question_520_true_answer
import drivelicensetest.composeapp.generated.resources.question_521
import drivelicensetest.composeapp.generated.resources.question_521_answer_1
import drivelicensetest.composeapp.generated.resources.question_521_answer_2
import drivelicensetest.composeapp.generated.resources.question_521_answer_3
import drivelicensetest.composeapp.generated.resources.question_521_true_answer
import drivelicensetest.composeapp.generated.resources.question_522
import drivelicensetest.composeapp.generated.resources.question_522_answer_1
import drivelicensetest.composeapp.generated.resources.question_522_answer_2
import drivelicensetest.composeapp.generated.resources.question_522_answer_3
import drivelicensetest.composeapp.generated.resources.question_522_true_answer
import drivelicensetest.composeapp.generated.resources.question_523
import drivelicensetest.composeapp.generated.resources.question_523_answer_1
import drivelicensetest.composeapp.generated.resources.question_523_answer_2
import drivelicensetest.composeapp.generated.resources.question_523_true_answer
import drivelicensetest.composeapp.generated.resources.question_524
import drivelicensetest.composeapp.generated.resources.question_524_answer_1
import drivelicensetest.composeapp.generated.resources.question_524_answer_2
import drivelicensetest.composeapp.generated.resources.question_524_true_answer
import drivelicensetest.composeapp.generated.resources.question_525
import drivelicensetest.composeapp.generated.resources.question_525_answer_1
import drivelicensetest.composeapp.generated.resources.question_525_answer_2
import drivelicensetest.composeapp.generated.resources.question_525_answer_3
import drivelicensetest.composeapp.generated.resources.question_525_true_answer
import drivelicensetest.composeapp.generated.resources.question_526
import drivelicensetest.composeapp.generated.resources.question_526_answer_1
import drivelicensetest.composeapp.generated.resources.question_526_answer_2
import drivelicensetest.composeapp.generated.resources.question_526_true_answer
import drivelicensetest.composeapp.generated.resources.question_527
import drivelicensetest.composeapp.generated.resources.question_527_answer_1
import drivelicensetest.composeapp.generated.resources.question_527_answer_2
import drivelicensetest.composeapp.generated.resources.question_527_answer_3
import drivelicensetest.composeapp.generated.resources.question_527_true_answer
import drivelicensetest.composeapp.generated.resources.question_528
import drivelicensetest.composeapp.generated.resources.question_528_answer_1
import drivelicensetest.composeapp.generated.resources.question_528_answer_2
import drivelicensetest.composeapp.generated.resources.question_528_true_answer
import drivelicensetest.composeapp.generated.resources.question_529
import drivelicensetest.composeapp.generated.resources.question_529_answer_1
import drivelicensetest.composeapp.generated.resources.question_529_answer_2
import drivelicensetest.composeapp.generated.resources.question_529_true_answer
import drivelicensetest.composeapp.generated.resources.question_530
import drivelicensetest.composeapp.generated.resources.question_530_answer_1
import drivelicensetest.composeapp.generated.resources.question_530_answer_2
import drivelicensetest.composeapp.generated.resources.question_530_true_answer
import drivelicensetest.composeapp.generated.resources.question_531
import drivelicensetest.composeapp.generated.resources.question_531_answer_1
import drivelicensetest.composeapp.generated.resources.question_531_answer_2
import drivelicensetest.composeapp.generated.resources.question_531_true_answer
import drivelicensetest.composeapp.generated.resources.question_532
import drivelicensetest.composeapp.generated.resources.question_532_answer_1
import drivelicensetest.composeapp.generated.resources.question_532_answer_2
import drivelicensetest.composeapp.generated.resources.question_532_answer_3
import drivelicensetest.composeapp.generated.resources.question_532_true_answer
import drivelicensetest.composeapp.generated.resources.question_533
import drivelicensetest.composeapp.generated.resources.question_533_answer_1
import drivelicensetest.composeapp.generated.resources.question_533_answer_2
import drivelicensetest.composeapp.generated.resources.question_533_answer_3
import drivelicensetest.composeapp.generated.resources.question_533_true_answer
import drivelicensetest.composeapp.generated.resources.question_534
import drivelicensetest.composeapp.generated.resources.question_534_answer_1
import drivelicensetest.composeapp.generated.resources.question_534_answer_2
import drivelicensetest.composeapp.generated.resources.question_534_answer_3
import drivelicensetest.composeapp.generated.resources.question_534_true_answer
import drivelicensetest.composeapp.generated.resources.question_535
import drivelicensetest.composeapp.generated.resources.question_535_answer_1
import drivelicensetest.composeapp.generated.resources.question_535_answer_2
import drivelicensetest.composeapp.generated.resources.question_535_answer_3
import drivelicensetest.composeapp.generated.resources.question_535_true_answer
import drivelicensetest.composeapp.generated.resources.question_536
import drivelicensetest.composeapp.generated.resources.question_536_answer_1
import drivelicensetest.composeapp.generated.resources.question_536_answer_2
import drivelicensetest.composeapp.generated.resources.question_536_answer_3
import drivelicensetest.composeapp.generated.resources.question_536_true_answer
import drivelicensetest.composeapp.generated.resources.question_537
import drivelicensetest.composeapp.generated.resources.question_537_answer_1
import drivelicensetest.composeapp.generated.resources.question_537_answer_2
import drivelicensetest.composeapp.generated.resources.question_537_true_answer
import drivelicensetest.composeapp.generated.resources.question_538
import drivelicensetest.composeapp.generated.resources.question_538_answer_1
import drivelicensetest.composeapp.generated.resources.question_538_answer_2
import drivelicensetest.composeapp.generated.resources.question_538_true_answer
import drivelicensetest.composeapp.generated.resources.question_539
import drivelicensetest.composeapp.generated.resources.question_539_answer_1
import drivelicensetest.composeapp.generated.resources.question_539_answer_2
import drivelicensetest.composeapp.generated.resources.question_539_answer_3
import drivelicensetest.composeapp.generated.resources.question_539_answer_4
import drivelicensetest.composeapp.generated.resources.question_539_true_answer
import drivelicensetest.composeapp.generated.resources.question_540
import drivelicensetest.composeapp.generated.resources.question_540_answer_1
import drivelicensetest.composeapp.generated.resources.question_540_answer_2
import drivelicensetest.composeapp.generated.resources.question_540_true_answer
import drivelicensetest.composeapp.generated.resources.question_541
import drivelicensetest.composeapp.generated.resources.question_541_answer_1
import drivelicensetest.composeapp.generated.resources.question_541_answer_2
import drivelicensetest.composeapp.generated.resources.question_541_true_answer
import drivelicensetest.composeapp.generated.resources.question_542
import drivelicensetest.composeapp.generated.resources.question_542_answer_1
import drivelicensetest.composeapp.generated.resources.question_542_answer_2
import drivelicensetest.composeapp.generated.resources.question_542_true_answer
import drivelicensetest.composeapp.generated.resources.question_543
import drivelicensetest.composeapp.generated.resources.question_543_answer_1
import drivelicensetest.composeapp.generated.resources.question_543_answer_2
import drivelicensetest.composeapp.generated.resources.question_543_answer_3
import drivelicensetest.composeapp.generated.resources.question_543_true_answer
import drivelicensetest.composeapp.generated.resources.question_544
import drivelicensetest.composeapp.generated.resources.question_544_answer_1
import drivelicensetest.composeapp.generated.resources.question_544_answer_2
import drivelicensetest.composeapp.generated.resources.question_544_answer_3
import drivelicensetest.composeapp.generated.resources.question_544_true_answer
import drivelicensetest.composeapp.generated.resources.question_545
import drivelicensetest.composeapp.generated.resources.question_545_answer_1
import drivelicensetest.composeapp.generated.resources.question_545_answer_2
import drivelicensetest.composeapp.generated.resources.question_545_answer_3
import drivelicensetest.composeapp.generated.resources.question_545_answer_4
import drivelicensetest.composeapp.generated.resources.question_545_true_answer
import drivelicensetest.composeapp.generated.resources.question_546
import drivelicensetest.composeapp.generated.resources.question_546_answer_1
import drivelicensetest.composeapp.generated.resources.question_546_answer_2
import drivelicensetest.composeapp.generated.resources.question_546_answer_3
import drivelicensetest.composeapp.generated.resources.question_546_true_answer
import drivelicensetest.composeapp.generated.resources.question_547
import drivelicensetest.composeapp.generated.resources.question_547_answer_1
import drivelicensetest.composeapp.generated.resources.question_547_answer_2
import drivelicensetest.composeapp.generated.resources.question_547_answer_3
import drivelicensetest.composeapp.generated.resources.question_547_true_answer
import drivelicensetest.composeapp.generated.resources.question_548
import drivelicensetest.composeapp.generated.resources.question_548_answer_1
import drivelicensetest.composeapp.generated.resources.question_548_answer_2
import drivelicensetest.composeapp.generated.resources.question_548_answer_3
import drivelicensetest.composeapp.generated.resources.question_548_true_answer
import drivelicensetest.composeapp.generated.resources.question_549
import drivelicensetest.composeapp.generated.resources.question_549_answer_1
import drivelicensetest.composeapp.generated.resources.question_549_answer_2
import drivelicensetest.composeapp.generated.resources.question_549_true_answer
import drivelicensetest.composeapp.generated.resources.question_550
import drivelicensetest.composeapp.generated.resources.question_550_answer_1
import drivelicensetest.composeapp.generated.resources.question_550_answer_2
import drivelicensetest.composeapp.generated.resources.question_550_answer_3
import drivelicensetest.composeapp.generated.resources.question_550_answer_4
import drivelicensetest.composeapp.generated.resources.question_550_true_answer
import drivelicensetest.composeapp.generated.resources.question_551
import drivelicensetest.composeapp.generated.resources.question_551_answer_1
import drivelicensetest.composeapp.generated.resources.question_551_answer_2
import drivelicensetest.composeapp.generated.resources.question_551_true_answer
import drivelicensetest.composeapp.generated.resources.question_552
import drivelicensetest.composeapp.generated.resources.question_552_answer_1
import drivelicensetest.composeapp.generated.resources.question_552_answer_2
import drivelicensetest.composeapp.generated.resources.question_552_answer_3
import drivelicensetest.composeapp.generated.resources.question_552_true_answer
import drivelicensetest.composeapp.generated.resources.question_553
import drivelicensetest.composeapp.generated.resources.question_553_answer_1
import drivelicensetest.composeapp.generated.resources.question_553_answer_2
import drivelicensetest.composeapp.generated.resources.question_553_answer_3
import drivelicensetest.composeapp.generated.resources.question_553_true_answer
import drivelicensetest.composeapp.generated.resources.question_554
import drivelicensetest.composeapp.generated.resources.question_554_answer_1
import drivelicensetest.composeapp.generated.resources.question_554_answer_2
import drivelicensetest.composeapp.generated.resources.question_554_answer_3
import drivelicensetest.composeapp.generated.resources.question_554_true_answer
import drivelicensetest.composeapp.generated.resources.question_555
import drivelicensetest.composeapp.generated.resources.question_555_answer_1
import drivelicensetest.composeapp.generated.resources.question_555_answer_2
import drivelicensetest.composeapp.generated.resources.question_555_true_answer
import drivelicensetest.composeapp.generated.resources.question_556
import drivelicensetest.composeapp.generated.resources.question_556_answer_1
import drivelicensetest.composeapp.generated.resources.question_556_answer_2
import drivelicensetest.composeapp.generated.resources.question_556_true_answer
import drivelicensetest.composeapp.generated.resources.question_557
import drivelicensetest.composeapp.generated.resources.question_557_answer_1
import drivelicensetest.composeapp.generated.resources.question_557_answer_2
import drivelicensetest.composeapp.generated.resources.question_557_answer_3
import drivelicensetest.composeapp.generated.resources.question_557_true_answer
import drivelicensetest.composeapp.generated.resources.question_558
import drivelicensetest.composeapp.generated.resources.question_558_answer_1
import drivelicensetest.composeapp.generated.resources.question_558_answer_2
import drivelicensetest.composeapp.generated.resources.question_558_answer_3
import drivelicensetest.composeapp.generated.resources.question_558_true_answer
import drivelicensetest.composeapp.generated.resources.question_559
import drivelicensetest.composeapp.generated.resources.question_559_answer_1
import drivelicensetest.composeapp.generated.resources.question_559_answer_2
import drivelicensetest.composeapp.generated.resources.question_559_answer_3
import drivelicensetest.composeapp.generated.resources.question_559_true_answer
import drivelicensetest.composeapp.generated.resources.question_560
import drivelicensetest.composeapp.generated.resources.question_560_answer_1
import drivelicensetest.composeapp.generated.resources.question_560_answer_2
import drivelicensetest.composeapp.generated.resources.question_560_answer_3
import drivelicensetest.composeapp.generated.resources.question_560_true_answer
import drivelicensetest.composeapp.generated.resources.question_561
import drivelicensetest.composeapp.generated.resources.question_561_answer_1
import drivelicensetest.composeapp.generated.resources.question_561_answer_2
import drivelicensetest.composeapp.generated.resources.question_561_answer_3
import drivelicensetest.composeapp.generated.resources.question_561_true_answer
import drivelicensetest.composeapp.generated.resources.question_562
import drivelicensetest.composeapp.generated.resources.question_562_answer_1
import drivelicensetest.composeapp.generated.resources.question_562_answer_2
import drivelicensetest.composeapp.generated.resources.question_562_true_answer
import drivelicensetest.composeapp.generated.resources.question_563
import drivelicensetest.composeapp.generated.resources.question_563_answer_1
import drivelicensetest.composeapp.generated.resources.question_563_answer_2
import drivelicensetest.composeapp.generated.resources.question_563_true_answer
import drivelicensetest.composeapp.generated.resources.question_564
import drivelicensetest.composeapp.generated.resources.question_564_answer_1
import drivelicensetest.composeapp.generated.resources.question_564_answer_2
import drivelicensetest.composeapp.generated.resources.question_564_answer_3
import drivelicensetest.composeapp.generated.resources.question_564_true_answer
import drivelicensetest.composeapp.generated.resources.question_565
import drivelicensetest.composeapp.generated.resources.question_565_answer_1
import drivelicensetest.composeapp.generated.resources.question_565_answer_2
import drivelicensetest.composeapp.generated.resources.question_565_true_answer
import drivelicensetest.composeapp.generated.resources.question_566
import drivelicensetest.composeapp.generated.resources.question_566_answer_1
import drivelicensetest.composeapp.generated.resources.question_566_answer_2
import drivelicensetest.composeapp.generated.resources.question_566_answer_3
import drivelicensetest.composeapp.generated.resources.question_566_true_answer
import drivelicensetest.composeapp.generated.resources.question_567
import drivelicensetest.composeapp.generated.resources.question_567_answer_1
import drivelicensetest.composeapp.generated.resources.question_567_answer_2
import drivelicensetest.composeapp.generated.resources.question_567_true_answer
import drivelicensetest.composeapp.generated.resources.question_568
import drivelicensetest.composeapp.generated.resources.question_568_answer_1
import drivelicensetest.composeapp.generated.resources.question_568_answer_2
import drivelicensetest.composeapp.generated.resources.question_568_answer_3
import drivelicensetest.composeapp.generated.resources.question_568_true_answer
import drivelicensetest.composeapp.generated.resources.question_569
import drivelicensetest.composeapp.generated.resources.question_569_answer_1
import drivelicensetest.composeapp.generated.resources.question_569_answer_2
import drivelicensetest.composeapp.generated.resources.question_569_true_answer
import drivelicensetest.composeapp.generated.resources.question_570
import drivelicensetest.composeapp.generated.resources.question_570_answer_1
import drivelicensetest.composeapp.generated.resources.question_570_answer_2
import drivelicensetest.composeapp.generated.resources.question_570_answer_3
import drivelicensetest.composeapp.generated.resources.question_570_true_answer
import drivelicensetest.composeapp.generated.resources.question_571
import drivelicensetest.composeapp.generated.resources.question_571_answer_1
import drivelicensetest.composeapp.generated.resources.question_571_answer_2
import drivelicensetest.composeapp.generated.resources.question_571_answer_3
import drivelicensetest.composeapp.generated.resources.question_571_answer_4
import drivelicensetest.composeapp.generated.resources.question_571_true_answer
import drivelicensetest.composeapp.generated.resources.question_572
import drivelicensetest.composeapp.generated.resources.question_572_answer_1
import drivelicensetest.composeapp.generated.resources.question_572_answer_2
import drivelicensetest.composeapp.generated.resources.question_572_answer_3
import drivelicensetest.composeapp.generated.resources.question_572_true_answer
import drivelicensetest.composeapp.generated.resources.question_573
import drivelicensetest.composeapp.generated.resources.question_573_answer_1
import drivelicensetest.composeapp.generated.resources.question_573_answer_2
import drivelicensetest.composeapp.generated.resources.question_573_answer_3
import drivelicensetest.composeapp.generated.resources.question_573_true_answer
import drivelicensetest.composeapp.generated.resources.question_574
import drivelicensetest.composeapp.generated.resources.question_574_answer_1
import drivelicensetest.composeapp.generated.resources.question_574_answer_2
import drivelicensetest.composeapp.generated.resources.question_574_answer_3
import drivelicensetest.composeapp.generated.resources.question_574_true_answer
import drivelicensetest.composeapp.generated.resources.question_575
import drivelicensetest.composeapp.generated.resources.question_575_answer_1
import drivelicensetest.composeapp.generated.resources.question_575_answer_2
import drivelicensetest.composeapp.generated.resources.question_575_true_answer
import drivelicensetest.composeapp.generated.resources.question_576
import drivelicensetest.composeapp.generated.resources.question_576_answer_1
import drivelicensetest.composeapp.generated.resources.question_576_answer_2
import drivelicensetest.composeapp.generated.resources.question_576_answer_3
import drivelicensetest.composeapp.generated.resources.question_576_true_answer
import drivelicensetest.composeapp.generated.resources.question_577
import drivelicensetest.composeapp.generated.resources.question_577_answer_1
import drivelicensetest.composeapp.generated.resources.question_577_answer_2
import drivelicensetest.composeapp.generated.resources.question_577_true_answer
import drivelicensetest.composeapp.generated.resources.question_578
import drivelicensetest.composeapp.generated.resources.question_578_answer_1
import drivelicensetest.composeapp.generated.resources.question_578_answer_2
import drivelicensetest.composeapp.generated.resources.question_578_answer_3
import drivelicensetest.composeapp.generated.resources.question_578_true_answer
import drivelicensetest.composeapp.generated.resources.question_579
import drivelicensetest.composeapp.generated.resources.question_579_answer_1
import drivelicensetest.composeapp.generated.resources.question_579_answer_2
import drivelicensetest.composeapp.generated.resources.question_579_answer_3
import drivelicensetest.composeapp.generated.resources.question_579_true_answer
import drivelicensetest.composeapp.generated.resources.question_580
import drivelicensetest.composeapp.generated.resources.question_580_answer_1
import drivelicensetest.composeapp.generated.resources.question_580_answer_2
import drivelicensetest.composeapp.generated.resources.question_580_true_answer
import drivelicensetest.composeapp.generated.resources.question_581
import drivelicensetest.composeapp.generated.resources.question_581_answer_1
import drivelicensetest.composeapp.generated.resources.question_581_answer_2
import drivelicensetest.composeapp.generated.resources.question_581_answer_3
import drivelicensetest.composeapp.generated.resources.question_581_true_answer
import drivelicensetest.composeapp.generated.resources.question_582
import drivelicensetest.composeapp.generated.resources.question_582_answer_1
import drivelicensetest.composeapp.generated.resources.question_582_answer_2
import drivelicensetest.composeapp.generated.resources.question_582_true_answer
import drivelicensetest.composeapp.generated.resources.question_583
import drivelicensetest.composeapp.generated.resources.question_583_answer_1
import drivelicensetest.composeapp.generated.resources.question_583_answer_2
import drivelicensetest.composeapp.generated.resources.question_583_answer_3
import drivelicensetest.composeapp.generated.resources.question_583_true_answer
import drivelicensetest.composeapp.generated.resources.question_584
import drivelicensetest.composeapp.generated.resources.question_584_answer_1
import drivelicensetest.composeapp.generated.resources.question_584_answer_2
import drivelicensetest.composeapp.generated.resources.question_584_true_answer
import drivelicensetest.composeapp.generated.resources.question_585
import drivelicensetest.composeapp.generated.resources.question_585_answer_1
import drivelicensetest.composeapp.generated.resources.question_585_answer_2
import drivelicensetest.composeapp.generated.resources.question_585_true_answer
import drivelicensetest.composeapp.generated.resources.question_586
import drivelicensetest.composeapp.generated.resources.question_586_answer_1
import drivelicensetest.composeapp.generated.resources.question_586_answer_2
import drivelicensetest.composeapp.generated.resources.question_586_answer_3
import drivelicensetest.composeapp.generated.resources.question_586_true_answer
import drivelicensetest.composeapp.generated.resources.question_587
import drivelicensetest.composeapp.generated.resources.question_587_answer_1
import drivelicensetest.composeapp.generated.resources.question_587_answer_2
import drivelicensetest.composeapp.generated.resources.question_587_answer_3
import drivelicensetest.composeapp.generated.resources.question_587_answer_4
import drivelicensetest.composeapp.generated.resources.question_587_true_answer
import drivelicensetest.composeapp.generated.resources.question_588
import drivelicensetest.composeapp.generated.resources.question_588_answer_1
import drivelicensetest.composeapp.generated.resources.question_588_answer_2
import drivelicensetest.composeapp.generated.resources.question_588_true_answer
import drivelicensetest.composeapp.generated.resources.question_589
import drivelicensetest.composeapp.generated.resources.question_589_answer_1
import drivelicensetest.composeapp.generated.resources.question_589_answer_2
import drivelicensetest.composeapp.generated.resources.question_589_answer_3
import drivelicensetest.composeapp.generated.resources.question_589_answer_4
import drivelicensetest.composeapp.generated.resources.question_589_true_answer
import drivelicensetest.composeapp.generated.resources.question_590
import drivelicensetest.composeapp.generated.resources.question_590_answer_1
import drivelicensetest.composeapp.generated.resources.question_590_answer_2
import drivelicensetest.composeapp.generated.resources.question_590_answer_3
import drivelicensetest.composeapp.generated.resources.question_590_answer_4
import drivelicensetest.composeapp.generated.resources.question_590_true_answer
import drivelicensetest.composeapp.generated.resources.question_591
import drivelicensetest.composeapp.generated.resources.question_591_answer_1
import drivelicensetest.composeapp.generated.resources.question_591_answer_2
import drivelicensetest.composeapp.generated.resources.question_591_true_answer
import drivelicensetest.composeapp.generated.resources.question_592
import drivelicensetest.composeapp.generated.resources.question_592_answer_1
import drivelicensetest.composeapp.generated.resources.question_592_answer_2
import drivelicensetest.composeapp.generated.resources.question_592_answer_3
import drivelicensetest.composeapp.generated.resources.question_592_true_answer
import drivelicensetest.composeapp.generated.resources.question_593
import drivelicensetest.composeapp.generated.resources.question_593_answer_1
import drivelicensetest.composeapp.generated.resources.question_593_answer_2
import drivelicensetest.composeapp.generated.resources.question_593_answer_3
import drivelicensetest.composeapp.generated.resources.question_593_true_answer
import drivelicensetest.composeapp.generated.resources.question_594
import drivelicensetest.composeapp.generated.resources.question_594_answer_1
import drivelicensetest.composeapp.generated.resources.question_594_answer_2
import drivelicensetest.composeapp.generated.resources.question_594_answer_3
import drivelicensetest.composeapp.generated.resources.question_594_true_answer
import drivelicensetest.composeapp.generated.resources.question_595
import drivelicensetest.composeapp.generated.resources.question_595_answer_1
import drivelicensetest.composeapp.generated.resources.question_595_answer_2
import drivelicensetest.composeapp.generated.resources.question_595_true_answer
import drivelicensetest.composeapp.generated.resources.question_596
import drivelicensetest.composeapp.generated.resources.question_596_answer_1
import drivelicensetest.composeapp.generated.resources.question_596_answer_2
import drivelicensetest.composeapp.generated.resources.question_596_true_answer
import drivelicensetest.composeapp.generated.resources.question_597
import drivelicensetest.composeapp.generated.resources.question_597_answer_1
import drivelicensetest.composeapp.generated.resources.question_597_answer_2
import drivelicensetest.composeapp.generated.resources.question_597_answer_3
import drivelicensetest.composeapp.generated.resources.question_597_true_answer
import drivelicensetest.composeapp.generated.resources.question_598
import drivelicensetest.composeapp.generated.resources.question_598_answer_1
import drivelicensetest.composeapp.generated.resources.question_598_answer_2
import drivelicensetest.composeapp.generated.resources.question_598_true_answer
import drivelicensetest.composeapp.generated.resources.question_599
import drivelicensetest.composeapp.generated.resources.question_599_answer_1
import drivelicensetest.composeapp.generated.resources.question_599_answer_2
import drivelicensetest.composeapp.generated.resources.question_599_true_answer
import drivelicensetest.composeapp.generated.resources.question_600
import drivelicensetest.composeapp.generated.resources.question_600_answer_1
import drivelicensetest.composeapp.generated.resources.question_600_answer_2
import drivelicensetest.composeapp.generated.resources.question_600_true_answer
import drivelicensetest.composeapp.generated.resources.question_601
import drivelicensetest.composeapp.generated.resources.question_601_answer_1
import drivelicensetest.composeapp.generated.resources.question_601_answer_2
import drivelicensetest.composeapp.generated.resources.question_601_answer_3
import drivelicensetest.composeapp.generated.resources.question_601_true_answer
import drivelicensetest.composeapp.generated.resources.question_602
import drivelicensetest.composeapp.generated.resources.question_602_answer_1
import drivelicensetest.composeapp.generated.resources.question_602_answer_2
import drivelicensetest.composeapp.generated.resources.question_602_answer_3
import drivelicensetest.composeapp.generated.resources.question_602_true_answer
import drivelicensetest.composeapp.generated.resources.question_603
import drivelicensetest.composeapp.generated.resources.question_603_answer_1
import drivelicensetest.composeapp.generated.resources.question_603_answer_2
import drivelicensetest.composeapp.generated.resources.question_603_answer_3
import drivelicensetest.composeapp.generated.resources.question_603_true_answer
import drivelicensetest.composeapp.generated.resources.question_604
import drivelicensetest.composeapp.generated.resources.question_604_answer_1
import drivelicensetest.composeapp.generated.resources.question_604_answer_2
import drivelicensetest.composeapp.generated.resources.question_604_answer_3
import drivelicensetest.composeapp.generated.resources.question_604_answer_4
import drivelicensetest.composeapp.generated.resources.question_604_true_answer
import drivelicensetest.composeapp.generated.resources.question_605
import drivelicensetest.composeapp.generated.resources.question_605_answer_1
import drivelicensetest.composeapp.generated.resources.question_605_answer_2
import drivelicensetest.composeapp.generated.resources.question_605_answer_3
import drivelicensetest.composeapp.generated.resources.question_605_true_answer
import drivelicensetest.composeapp.generated.resources.question_606
import drivelicensetest.composeapp.generated.resources.question_606_answer_1
import drivelicensetest.composeapp.generated.resources.question_606_answer_2
import drivelicensetest.composeapp.generated.resources.question_606_answer_3
import drivelicensetest.composeapp.generated.resources.question_606_true_answer
import drivelicensetest.composeapp.generated.resources.question_607
import drivelicensetest.composeapp.generated.resources.question_607_answer_1
import drivelicensetest.composeapp.generated.resources.question_607_answer_2
import drivelicensetest.composeapp.generated.resources.question_607_answer_3
import drivelicensetest.composeapp.generated.resources.question_607_answer_4
import drivelicensetest.composeapp.generated.resources.question_607_true_answer
import drivelicensetest.composeapp.generated.resources.question_608
import drivelicensetest.composeapp.generated.resources.question_608_answer_1
import drivelicensetest.composeapp.generated.resources.question_608_answer_2
import drivelicensetest.composeapp.generated.resources.question_608_answer_3
import drivelicensetest.composeapp.generated.resources.question_608_true_answer

class QuestionGroup5 {

    private val questionsGroup5 = listOf(
        Question(
            question = Res.string.question_474,
            image = "x",
            answers = listOf(
                Res.string.question_474_answer_1,
                Res.string.question_474_answer_2,
                Res.string.question_474_answer_3
            ),
            trueAnswer = Res.string.question_474_true_answer
        ),

        Question(
            question = Res.string.question_475,
            image = "x",
            answers = listOf(
                Res.string.question_475_answer_1,
                Res.string.question_475_answer_2,
                Res.string.question_475_answer_3,
                Res.string.question_475_answer_4
            ),
            trueAnswer = Res.string.question_475_true_answer
        ),

        Question(
            question = Res.string.question_476,
            image = "x",
            answers = listOf(
                Res.string.question_476_answer_1,
                Res.string.question_476_answer_2,
                Res.string.question_476_answer_3
            ),
            trueAnswer = Res.string.question_476_true_answer
        ),

        Question(
            question = Res.string.question_477,
            image = "x",
            answers = listOf(
                Res.string.question_477_answer_1,
                Res.string.question_477_answer_2
            ),
            trueAnswer = Res.string.question_477_true_answer
        ),

        Question(
            question = Res.string.question_478,
            image = "x",
            answers = listOf(
                Res.string.question_478_answer_1,
                Res.string.question_478_answer_2,
                Res.string.question_478_answer_3
            ),
            trueAnswer = Res.string.question_478_true_answer
        ),

        Question(
            question = Res.string.question_479,
            image = "x",
            answers = listOf(
                Res.string.question_479_answer_1,
                Res.string.question_479_answer_2,
                Res.string.question_479_answer_3
            ),
            trueAnswer = Res.string.question_479_true_answer
        ),

        Question(
            question = Res.string.question_480,
            image = "x",
            answers = listOf(
                Res.string.question_480_answer_1,
                Res.string.question_480_answer_2,
                Res.string.question_480_answer_3
            ),
            trueAnswer = Res.string.question_480_true_answer
        ),

        Question(
            question = Res.string.question_481,
            image = "x",
            answers = listOf(
                Res.string.question_481_answer_1,
                Res.string.question_481_answer_2,
                Res.string.question_481_answer_3
            ),
            trueAnswer = Res.string.question_481_true_answer
        ),

        Question(
            question = Res.string.question_482,
            image = "x",
            answers = listOf(
                Res.string.question_482_answer_1,
                Res.string.question_482_answer_2,
                Res.string.question_482_answer_3
            ),
            trueAnswer = Res.string.question_482_true_answer
        ),

        Question(
            question = Res.string.question_483,
            image = "x",
            answers = listOf(
                Res.string.question_483_answer_1,
                Res.string.question_483_answer_2,
                Res.string.question_483_answer_3
            ),
            trueAnswer = Res.string.question_483_true_answer
        ),

        Question(
            Res.string.question_484,
            image = "x",
            answers = listOf(
                Res.string.question_484_answer_1,
                Res.string.question_484_answer_2,
                Res.string.question_484_answer_3,
                Res.string.question_484_answer_4
            ),
            trueAnswer = Res.string.question_484_true_answer
        ),

        Question(
            Res.string.question_485,
            image = "x",
            answers = listOf(
                Res.string.question_485_answer_1,
                Res.string.question_485_answer_2
            ),
            trueAnswer = Res.string.question_485_true_answer
        ),

        Question(
            question = Res.string.question_486,
            image = "x",
            answers = listOf(
                Res.string.question_486_answer_1,
                Res.string.question_486_answer_2,
                Res.string.question_486_answer_3,
                Res.string.question_486_answer_4
            ),
            trueAnswer = Res.string.question_486_true_answer
        ),

        Question(
            question = Res.string.question_487,
            image = "x",
            answers = listOf(
                Res.string.question_487_answer_1,
                Res.string.question_487_answer_2,
                Res.string.question_487_answer_3
            ),
            trueAnswer = Res.string.question_487_true_answer
        ),

        Question(
            question = Res.string.question_488,
            image = "x",
            answers = listOf(
                Res.string.question_488_answer_1,
                Res.string.question_488_answer_2,
                Res.string.question_488_answer_3
            ),
            trueAnswer = Res.string.question_488_true_answer
        ),

        Question(
            question = Res.string.question_489,
            image = "x",
            answers = listOf(
                Res.string.question_489_answer_1,
                Res.string.question_489_answer_2,
                Res.string.question_489_answer_3
            ),
            trueAnswer = Res.string.question_489_true_answer
        ),

        Question(
            question = Res.string.question_490,
            image = "x",
            answers = listOf(
                Res.string.question_490_answer_1,
                Res.string.question_490_answer_2,
                Res.string.question_490_answer_3
            ),
            trueAnswer = Res.string.question_490_true_answer
        ),

        Question(
            question = Res.string.question_491,
            image = "x",
            answers = listOf(
                Res.string.question_491_answer_1,
                Res.string.question_491_answer_2,
                Res.string.question_491_answer_3
            ),
            trueAnswer = Res.string.question_491_true_answer
        ),

        Question(
            question = Res.string.question_492,
            image = "x",
            answers = listOf(
                Res.string.question_492_answer_1,
                Res.string.question_492_answer_2
            ),
            trueAnswer = Res.string.question_492_true_answer
        ),

        Question(
            question = Res.string.question_493,
            image = "x",
            answers = listOf(
                Res.string.question_493_answer_1,
                Res.string.question_493_answer_2,
                Res.string.question_493_answer_3
            ),
            trueAnswer = Res.string.question_493_true_answer
        ),

        Question(
            question = Res.string.question_494,
            image = "x",
            answers = listOf(
                Res.string.question_494_answer_1,
                Res.string.question_494_answer_2,
                Res.string.question_494_answer_3
            ),
            trueAnswer = Res.string.question_494_true_answer
        ),

        Question(
            question = Res.string.question_495,
            image = "x",
            answers = listOf(
                Res.string.question_495_answer_1,
                Res.string.question_495_answer_2,
                Res.string.question_495_answer_3,
                Res.string.question_495_answer_4
            ),
            trueAnswer = Res.string.question_495_true_answer
        ),

        Question(
            question = Res.string.question_496,
            image = "x",
            answers = listOf(
                Res.string.question_496_answer_1,
                Res.string.question_496_answer_2
            ),
            trueAnswer = Res.string.question_496_true_answer
        ),

        Question(
            question = Res.string.question_497,
            image = "x",
            answers = listOf(
                Res.string.question_497_answer_1,
                Res.string.question_497_answer_2
            ),
            trueAnswer = Res.string.question_497_true_answer
        ),

        Question(
            question = Res.string.question_498,
            image = "x",
            answers = listOf(
                Res.string.question_498_answer_1,
                Res.string.question_498_answer_2,
                Res.string.question_498_answer_3,
                Res.string.question_498_answer_4
            ),
            trueAnswer = Res.string.question_498_true_answer
        ),

        Question(
            question = Res.string.question_499,
            image = "x",
            answers = listOf(
                Res.string.question_499_answer_1,
                Res.string.question_499_answer_2,
                Res.string.question_499_answer_3
            ),
            trueAnswer = Res.string.question_499_true_answer
        ),

        Question(
            question = Res.string.question_500,
            image = "x",
            answers = listOf(
                Res.string.question_500_answer_1,
                Res.string.question_500_answer_2,
                Res.string.question_500_answer_3
            ),
            trueAnswer = Res.string.question_500_true_answer
        ),

        Question(
            question = Res.string.question_501,
            image = "x",
            answers = listOf(
                Res.string.question_501_answer_1,
                Res.string.question_501_answer_2,
                Res.string.question_501_answer_3
            ),
            trueAnswer = Res.string.question_501_true_answer
        ),

        Question(
            question = Res.string.question_502,
            image = "x",
            answers = listOf(
                Res.string.question_502_answer_1,
                Res.string.question_502_answer_2
            ),
            trueAnswer = Res.string.question_502_true_answer
        ),

        Question(
            question = Res.string.question_503,
            image = "x",
            answers = listOf(
                Res.string.question_503_answer_1,
                Res.string.question_503_answer_2,
                Res.string.question_503_answer_3
            ),
            trueAnswer = Res.string.question_503_true_answer
        ),

        Question(
            question = Res.string.question_504,
            image = "x",
            answers = listOf(
                Res.string.question_504_answer_1,
                Res.string.question_504_answer_2,
                Res.string.question_504_answer_3
            ),
            trueAnswer = Res.string.question_504_true_answer
        ),

        Question(
            question = Res.string.question_505,
            image = "x",
            answers = listOf(
                Res.string.question_505_answer_1,
                Res.string.question_505_answer_2
            ),
            trueAnswer = Res.string.question_505_true_answer
        ),

        Question(
            question = Res.string.question_506,
            image = "x",
            answers = listOf(
                Res.string.question_506_answer_1,
                Res.string.question_506_answer_2,
                Res.string.question_506_answer_3,
                Res.string.question_506_answer_4
            ),
            trueAnswer = Res.string.question_506_true_answer
        ),

        Question(
            question = Res.string.question_507,
            image = "x",
            answers = listOf(
                Res.string.question_507_answer_1,
                Res.string.question_507_answer_2
            ),
            trueAnswer = Res.string.question_507_true_answer
        ),

        Question(
            question = Res.string.question_508,
            image = "x",
            answers = listOf(
                Res.string.question_508_answer_1,
                Res.string.question_508_answer_2,
                Res.string.question_508_answer_3
            ),
            trueAnswer = Res.string.question_508_true_answer
        ),

        Question(
            question = Res.string.question_509,
            image = "x",
            answers = listOf(
                Res.string.question_509_answer_1,
                Res.string.question_509_answer_2
            ),
            trueAnswer = Res.string.question_509_true_answer
        ),

        Question(
            question = Res.string.question_510,
            image = "x",
            answers = listOf(
                Res.string.question_510_answer_1,
                Res.string.question_510_answer_2
            ),
            trueAnswer = Res.string.question_510_true_answer
        ),

        Question(
            question = Res.string.question_511,
            image = "x",
            answers = listOf(
                Res.string.question_511_answer_1,
                Res.string.question_511_answer_2
            ),
            trueAnswer = Res.string.question_511_true_answer
        ),

        Question(
            question = Res.string.question_512,
            image = "x",
            answers = listOf(
                Res.string.question_512_answer_1,
                Res.string.question_512_answer_2,
                Res.string.question_512_answer_3
            ),
            trueAnswer = Res.string.question_512_true_answer
        ),

        Question(
            question = Res.string.question_513,
            image = "x",
            answers = listOf(
                Res.string.question_513_answer_1,
                Res.string.question_513_answer_2
            ),
            trueAnswer = Res.string.question_513_true_answer
        ),

        Question(
            question = Res.string.question_514,
            image = "x",
            answers = listOf(
                Res.string.question_514_answer_1,
                Res.string.question_514_answer_2
            ),
            trueAnswer = Res.string.question_514_true_answer
        ),

        Question(
            question = Res.string.question_515,
            image = "x",
            answers = listOf(
                Res.string.question_515_answer_1,
                Res.string.question_515_answer_2,
                Res.string.question_515_answer_3
            ),
            trueAnswer = Res.string.question_515_true_answer
        ),

        Question(
            question = Res.string.question_516,
            image = "x",
            answers = listOf(
                Res.string.question_516_answer_1,
                Res.string.question_516_answer_2
            ),
            trueAnswer = Res.string.question_516_true_answer
        ),

        Question(
            question = Res.string.question_517,
            image = "x",
            answers = listOf(
                Res.string.question_517_answer_1,
                Res.string.question_517_answer_2,
                Res.string.question_517_answer_3
            ),
            trueAnswer = Res.string.question_517_true_answer
        ),

        Question(
            question = Res.string.question_518,
            image = "x",
            answers = listOf(
                Res.string.question_518_answer_1,
                Res.string.question_518_answer_2
            ),
            trueAnswer = Res.string.question_518_true_answer
        ),

        Question(
            question = Res.string.question_519,
            image = "x",
            answers = listOf(
                Res.string.question_519_answer_1,
                Res.string.question_519_answer_2,
                Res.string.question_519_answer_3
            ),
            trueAnswer = Res.string.question_519_true_answer
        ),

        Question(
            question = Res.string.question_520,
            image = "x",
            answers = listOf(
                Res.string.question_520_answer_1,
                Res.string.question_520_answer_2,
                Res.string.question_520_answer_3
            ),
            trueAnswer = Res.string.question_520_true_answer
        ),

        Question(
            question = Res.string.question_521,
            image = "x",
            answers = listOf(
                Res.string.question_521_answer_1,
                Res.string.question_521_answer_2,
                Res.string.question_521_answer_3
            ),
            trueAnswer = Res.string.question_521_true_answer
        ),

        Question(
            question = Res.string.question_522,
            image = "x",
            answers = listOf(
                Res.string.question_522_answer_1,
                Res.string.question_522_answer_2,
                Res.string.question_522_answer_3
            ),
            trueAnswer = Res.string.question_522_true_answer
        ),

        Question(
            question = Res.string.question_523,
            image = "x",
            answers = listOf(
                Res.string.question_523_answer_1,
                Res.string.question_523_answer_2
            ),
            trueAnswer = Res.string.question_523_true_answer
        ),

        Question(
            question = Res.string.question_524,
            image = "x",
            answers = listOf(
                Res.string.question_524_answer_1,
                Res.string.question_524_answer_2
            ),
            trueAnswer = Res.string.question_524_true_answer
        ),

        Question(
            question = Res.string.question_525,
            image = "x",
            answers = listOf(
                Res.string.question_525_answer_1,
                Res.string.question_525_answer_2,
                Res.string.question_525_answer_3
            ),
            trueAnswer = Res.string.question_525_true_answer
        ),

        Question(
            question = Res.string.question_526,
            image = "x",
            answers = listOf(
                Res.string.question_526_answer_1,
                Res.string.question_526_answer_2
            ),
            trueAnswer = Res.string.question_526_true_answer
        ),

        Question(
            question = Res.string.question_527,
            image = "x",
            answers = listOf(
                Res.string.question_527_answer_1,
                Res.string.question_527_answer_2,
                Res.string.question_527_answer_3
            ),
            trueAnswer = Res.string.question_527_true_answer
        ),

        Question(
            question = Res.string.question_528,
            image = "x",
            answers = listOf(
                Res.string.question_528_answer_1,
                Res.string.question_528_answer_2
            ),
            trueAnswer = Res.string.question_528_true_answer
        ),

        Question(
            question = Res.string.question_529,
            image = "x",
            answers = listOf(
                Res.string.question_529_answer_1,
                Res.string.question_529_answer_2
            ),
            trueAnswer = Res.string.question_529_true_answer
        ),

        Question(
            question = Res.string.question_530,
            image = "x",
            answers = listOf(
                Res.string.question_530_answer_1,
                Res.string.question_530_answer_2
            ),
            trueAnswer = Res.string.question_530_true_answer
        ),

        Question(
            question = Res.string.question_531,
            image = "x",
            answers = listOf(
                Res.string.question_531_answer_1,
                Res.string.question_531_answer_2
            ),
            trueAnswer = Res.string.question_531_true_answer
        ),

        Question(
            question = Res.string.question_532,
            image = "x",
            answers = listOf(
                Res.string.question_532_answer_1,
                Res.string.question_532_answer_2,
                Res.string.question_532_answer_3
            ),
            trueAnswer = Res.string.question_532_true_answer
        ),

        Question(
            question = Res.string.question_533,
            image = "x",
            answers = listOf(
                Res.string.question_533_answer_1,
                Res.string.question_533_answer_2,
                Res.string.question_533_answer_3
            ),
            trueAnswer = Res.string.question_533_true_answer
        ),

        Question(
            question = Res.string.question_534,
            image = "x",
            answers = listOf(
                Res.string.question_534_answer_1,
                Res.string.question_534_answer_2,
                Res.string.question_534_answer_3
            ),
            trueAnswer = Res.string.question_534_true_answer
        ),

        Question(
            question = Res.string.question_535,
            image = "x",
            answers = listOf(
                Res.string.question_535_answer_1,
                Res.string.question_535_answer_2,
                Res.string.question_535_answer_3
            ),
            trueAnswer = Res.string.question_535_true_answer
        ),

        Question(
            question = Res.string.question_536,
            image = "x",
            answers = listOf(
                Res.string.question_536_answer_1,
                Res.string.question_536_answer_2,
                Res.string.question_536_answer_3
            ),
            trueAnswer = Res.string.question_536_true_answer
        ),

        Question(
            question = Res.string.question_537,
            image = "x",
            answers = listOf(
                Res.string.question_537_answer_1,
                Res.string.question_537_answer_2
            ),
            trueAnswer = Res.string.question_537_true_answer
        ),

        Question(
            question = Res.string.question_538,
            image = "x",
            answers = listOf(
                Res.string.question_538_answer_1,
                Res.string.question_538_answer_2
            ),
            trueAnswer = Res.string.question_538_true_answer
        ),

        Question(
            question = Res.string.question_539,
            image = "x",
            answers = listOf(
                Res.string.question_539_answer_1,
                Res.string.question_539_answer_2,
                Res.string.question_539_answer_3,
                Res.string.question_539_answer_4
            ),
            trueAnswer = Res.string.question_539_true_answer
        ),

        Question(
            question = Res.string.question_540,
            image = "x",
            answers = listOf(
                Res.string.question_540_answer_1,
                Res.string.question_540_answer_2
            ),
            trueAnswer = Res.string.question_540_true_answer
        ),

        Question(
            question = Res.string.question_541,
            image = "x",
            answers = listOf(
                Res.string.question_541_answer_1,
                Res.string.question_541_answer_2
            ),
            trueAnswer = Res.string.question_541_true_answer
        ),

        Question(
            question = Res.string.question_542,
            image = "x",
            answers = listOf(
                Res.string.question_542_answer_1,
                Res.string.question_542_answer_2
            ),
            trueAnswer = Res.string.question_542_true_answer
        ),

        Question(
            question = Res.string.question_543,
            image = "x",
            answers = listOf(
                Res.string.question_543_answer_1,
                Res.string.question_543_answer_2,
                Res.string.question_543_answer_3
            ),
            trueAnswer = Res.string.question_543_true_answer
        ),

        Question(
            question = Res.string.question_544,
            image = "x",
            answers = listOf(
                Res.string.question_544_answer_1,
                Res.string.question_544_answer_2,
                Res.string.question_544_answer_3
            ),
            trueAnswer = Res.string.question_544_true_answer
        ),

        Question(
            question = Res.string.question_545,
            image = "x",
            answers = listOf(
                Res.string.question_545_answer_1,
                Res.string.question_545_answer_2,
                Res.string.question_545_answer_3,
                Res.string.question_545_answer_4
            ),
            trueAnswer = Res.string.question_545_true_answer
        ),

        Question(
            question = Res.string.question_546,
            image = "x",
            answers = listOf(
                Res.string.question_546_answer_1,
                Res.string.question_546_answer_2,
                Res.string.question_546_answer_3
            ),
            trueAnswer = Res.string.question_546_true_answer
        ),

        Question(
            question = Res.string.question_547,
            image = "x",
            answers = listOf(
                Res.string.question_547_answer_1,
                Res.string.question_547_answer_2,
                Res.string.question_547_answer_3
            ),
            trueAnswer = Res.string.question_547_true_answer
        ),

        Question(
            question = Res.string.question_548,
            image = "x",
            answers = listOf(
                Res.string.question_548_answer_1,
                Res.string.question_548_answer_2,
                Res.string.question_548_answer_3
            ),
            trueAnswer = Res.string.question_548_true_answer
        ),

        Question(
            question = Res.string.question_549,
            image = "x",
            answers = listOf(
                Res.string.question_549_answer_1,
                Res.string.question_549_answer_2
            ),
            trueAnswer = Res.string.question_549_true_answer
        ),

        Question(
            question = Res.string.question_550,
            image = "x",
            answers = listOf(
                Res.string.question_550_answer_1,
                Res.string.question_550_answer_2,
                Res.string.question_550_answer_3,
                Res.string.question_550_answer_4
            ),
            trueAnswer = Res.string.question_550_true_answer
        ),

        Question(
            question = Res.string.question_551,
            image = null,
            answers = listOf(
                Res.string.question_551_answer_1,
                Res.string.question_551_answer_2
            ),
            trueAnswer = Res.string.question_551_true_answer
        ),

        Question(
            question = Res.string.question_552,
            image = "x",
            answers = listOf(
                Res.string.question_552_answer_1,
                Res.string.question_552_answer_2,
                Res.string.question_552_answer_3
            ),
            trueAnswer = Res.string.question_552_true_answer
        ),

        Question(
            question = Res.string.question_553,
            image = "x",
            answers = listOf(
                Res.string.question_553_answer_1,
                Res.string.question_553_answer_2,
                Res.string.question_553_answer_3
            ),
            trueAnswer = Res.string.question_553_true_answer
        ),

        Question(
            question = Res.string.question_554,
            image = "x",
            answers = listOf(
                Res.string.question_554_answer_1,
                Res.string.question_554_answer_2,
                Res.string.question_554_answer_3
            ),
            trueAnswer = Res.string.question_554_true_answer
        ),

        Question(
            question = Res.string.question_555,
            image = "x",
            answers = listOf(
                Res.string.question_555_answer_1,
                Res.string.question_555_answer_2
            ),
            trueAnswer = Res.string.question_555_true_answer
        ),

        Question(
            question = Res.string.question_556,
            image = "x",
            answers = listOf(
                Res.string.question_556_answer_1,
                Res.string.question_556_answer_2
            ),
            trueAnswer = Res.string.question_556_true_answer
        ),

        Question(
            question = Res.string.question_557,
            image = "x",
            answers = listOf(
                Res.string.question_557_answer_1,
                Res.string.question_557_answer_2,
                Res.string.question_557_answer_3
            ),
            trueAnswer = Res.string.question_557_true_answer
        ),

        Question(
            question = Res.string.question_558,
            image = "x",
            answers = listOf(
                Res.string.question_558_answer_1,
                Res.string.question_558_answer_2,
                Res.string.question_558_answer_3
            ),
            trueAnswer = Res.string.question_558_true_answer
        ),

        Question(
            question = Res.string.question_559,
            image = "x",
            answers = listOf(
                Res.string.question_559_answer_1,
                Res.string.question_559_answer_2,
                Res.string.question_559_answer_3
            ),
            trueAnswer = Res.string.question_559_true_answer
        ),

        Question(
            question = Res.string.question_560,
            image = "x",
            answers = listOf(
                Res.string.question_560_answer_1,
                Res.string.question_560_answer_2,
                Res.string.question_560_answer_3
            ),
            trueAnswer = Res.string.question_560_true_answer
        ),

        Question(
            question = Res.string.question_561,
            image = "x",
            answers = listOf(
                Res.string.question_561_answer_1,
                Res.string.question_561_answer_2,
                Res.string.question_561_answer_3
            ),
            trueAnswer = Res.string.question_561_true_answer
        ),

        Question(
            question = Res.string.question_562,
            image = "x",
            answers = listOf(
                Res.string.question_562_answer_1,
                Res.string.question_562_answer_2
            ),
            trueAnswer = Res.string.question_562_true_answer
        ),

        Question(
            question = Res.string.question_563,
            image = "x",
            answers = listOf(
                Res.string.question_563_answer_1,
                Res.string.question_563_answer_2
            ),
            trueAnswer = Res.string.question_563_true_answer
        ),

        Question(
            question = Res.string.question_564,
            image = "x",
            answers = listOf(
                Res.string.question_564_answer_1,
                Res.string.question_564_answer_2,
                Res.string.question_564_answer_3
            ),
            trueAnswer = Res.string.question_564_true_answer
        ),

        Question(
            question = Res.string.question_565,
            image = "x",
            answers = listOf(
                Res.string.question_565_answer_1,
                Res.string.question_565_answer_2
            ),
            trueAnswer = Res.string.question_565_true_answer
        ),

        Question(
            question = Res.string.question_566,
            image = "x",
            answers = listOf(
                Res.string.question_566_answer_1,
                Res.string.question_566_answer_2,
                Res.string.question_566_answer_3
            ),
            trueAnswer = Res.string.question_566_true_answer
        ),

        Question(
            question = Res.string.question_567,
            image = "x",
            answers = listOf(
                Res.string.question_567_answer_1,
                Res.string.question_567_answer_2
            ),
            trueAnswer = Res.string.question_567_true_answer
        ),

        Question(
            question = Res.string.question_568,
            image = "x",
            answers = listOf(
                Res.string.question_568_answer_1,
                Res.string.question_568_answer_2,
                Res.string.question_568_answer_3
            ),
            trueAnswer = Res.string.question_568_true_answer
        ),

        Question(
            question = Res.string.question_569,
            image = "x",
            answers = listOf(
                Res.string.question_569_answer_1,
                Res.string.question_569_answer_2
            ),
            trueAnswer = Res.string.question_569_true_answer
        ),

        Question(
            question = Res.string.question_570,
            image = "x",
            answers = listOf(
                Res.string.question_570_answer_1,
                Res.string.question_570_answer_2,
                Res.string.question_570_answer_3
            ),
            trueAnswer = Res.string.question_570_true_answer
        ),

        Question(
            question = Res.string.question_571,
            image = "x",
            answers = listOf(
                Res.string.question_571_answer_1,
                Res.string.question_571_answer_2,
                Res.string.question_571_answer_3,
                Res.string.question_571_answer_4
            ),
            trueAnswer = Res.string.question_571_true_answer
        ),
        Question(
            question = Res.string.question_572,
            image = "x",
            answers = listOf(
                Res.string.question_572_answer_1,
                Res.string.question_572_answer_2,
                Res.string.question_572_answer_3
            ),
            trueAnswer = Res.string.question_572_true_answer
        ),

        Question(
            question = Res.string.question_573,
            image = "x",
            answers = listOf(
                Res.string.question_573_answer_1,
                Res.string.question_573_answer_2,
                Res.string.question_573_answer_3
            ),
            trueAnswer = Res.string.question_573_true_answer
        ),

        Question(
            question = Res.string.question_574,
            image = "x",
            answers = listOf(
                Res.string.question_574_answer_1,
                Res.string.question_574_answer_2,
                Res.string.question_574_answer_3
            ),
            trueAnswer = Res.string.question_574_true_answer
        ),

        Question(
            question = Res.string.question_575,
            image = "x",
            answers = listOf(
                Res.string.question_575_answer_1,
                Res.string.question_575_answer_2
            ),
            trueAnswer = Res.string.question_575_true_answer
        ),

        Question(
            question = Res.string.question_576,
            image = "x",
            answers = listOf(
                Res.string.question_576_answer_1,
                Res.string.question_576_answer_2,
                Res.string.question_576_answer_3
            ),
            trueAnswer = Res.string.question_576_true_answer
        ),

        Question(
            question = Res.string.question_577,
            image = "x",
            answers = listOf(
                Res.string.question_577_answer_1,
                Res.string.question_577_answer_2
            ),
            trueAnswer = Res.string.question_577_true_answer
        ),

        Question(
            question = Res.string.question_578,
            image = "x",
            answers = listOf(
                Res.string.question_578_answer_1,
                Res.string.question_578_answer_2,
                Res.string.question_578_answer_3
            ),
            trueAnswer = Res.string.question_578_true_answer
        ),

        Question(
            question = Res.string.question_579,
            image = "x",
            answers = listOf(
                Res.string.question_579_answer_1,
                Res.string.question_579_answer_2,
                Res.string.question_579_answer_3
            ),
            trueAnswer = Res.string.question_579_true_answer
        ),

        Question(
            question = Res.string.question_580,
            image = "x",
            answers = listOf(
                Res.string.question_580_answer_1,
                Res.string.question_580_answer_2
            ),
            trueAnswer = Res.string.question_580_true_answer
        ),
        Question(
            question = Res.string.question_581,
            image = "x",
            answers = listOf(
                Res.string.question_581_answer_1,
                Res.string.question_581_answer_2,
                Res.string.question_581_answer_3
            ),
            trueAnswer = Res.string.question_581_true_answer
        ),

        Question(
            question = Res.string.question_582,
            image = "x",
            answers = listOf(
                Res.string.question_582_answer_1,
                Res.string.question_582_answer_2
            ),
            trueAnswer = Res.string.question_582_true_answer
        ),

        Question(
            question = Res.string.question_583,
            image = "x",
            answers = listOf(
                Res.string.question_583_answer_1,
                Res.string.question_583_answer_2,
                Res.string.question_583_answer_3
            ),
            trueAnswer = Res.string.question_583_true_answer
        ),

        Question(
            question = Res.string.question_584,
            image = "x",
            answers = listOf(
                Res.string.question_584_answer_1,
                Res.string.question_584_answer_2
            ),
            trueAnswer = Res.string.question_584_true_answer
        ),

        Question(
            question = Res.string.question_585,
            image = "x",
            answers = listOf(
                Res.string.question_585_answer_1,
                Res.string.question_585_answer_2
            ),
            trueAnswer = Res.string.question_585_true_answer
        ),

        Question(
            question = Res.string.question_586,
            image = "x",
            answers = listOf(
                Res.string.question_586_answer_1,
                Res.string.question_586_answer_2,
                Res.string.question_586_answer_3
            ),
            trueAnswer = Res.string.question_586_true_answer
        ),

        Question(
            question = Res.string.question_587,
            image = "x",
            answers = listOf(
                Res.string.question_587_answer_1,
                Res.string.question_587_answer_2,
                Res.string.question_587_answer_3,
                Res.string.question_587_answer_4
            ),
            trueAnswer = Res.string.question_587_true_answer
        ),

        Question(
            question = Res.string.question_588,
            image = "x",
            answers = listOf(
                Res.string.question_588_answer_1,
                Res.string.question_588_answer_2
            ),
            trueAnswer = Res.string.question_588_true_answer
        ),

        Question(
            question = Res.string.question_589,
            image = "x",
            answers = listOf(
                Res.string.question_589_answer_1,
                Res.string.question_589_answer_2,
                Res.string.question_589_answer_3,
                Res.string.question_589_answer_4
            ),
            trueAnswer = Res.string.question_589_true_answer
        ),

        Question(
            question = Res.string.question_590,
            image = "x",
            answers = listOf(
                Res.string.question_590_answer_1,
                Res.string.question_590_answer_2,
                Res.string.question_590_answer_3,
                Res.string.question_590_answer_4
            ),
            trueAnswer = Res.string.question_590_true_answer
        ),

        Question(
            question = Res.string.question_591,
            image = "x",
            answers = listOf(
                Res.string.question_591_answer_1,
                Res.string.question_591_answer_2
            ),
            trueAnswer = Res.string.question_591_true_answer
        ),

        Question(
            question = Res.string.question_592,
            image = "x",
            answers = listOf(
                Res.string.question_592_answer_1,
                Res.string.question_592_answer_2,
                Res.string.question_592_answer_3
            ),
            trueAnswer = Res.string.question_592_true_answer
        ),

        Question(
            question = Res.string.question_593,
            image = "x",
            answers = listOf(
                Res.string.question_593_answer_1,
                Res.string.question_593_answer_2,
                Res.string.question_593_answer_3
            ),
            trueAnswer = Res.string.question_593_true_answer
        ),

        Question(
            question = Res.string.question_594,
            image = "x",
            answers = listOf(
                Res.string.question_594_answer_1,
                Res.string.question_594_answer_2,
                Res.string.question_594_answer_3
            ),
            trueAnswer = Res.string.question_594_true_answer
        ),

        Question(
            question = Res.string.question_595,
            image = "x",
            answers = listOf(
                Res.string.question_595_answer_1,
                Res.string.question_595_answer_2
            ),
            trueAnswer = Res.string.question_595_true_answer
        ),

        Question(
            question = Res.string.question_596,
            image = "x",
            answers = listOf(
                Res.string.question_596_answer_1,
                Res.string.question_596_answer_2
            ),
            trueAnswer = Res.string.question_596_true_answer
        ),

        Question(
            question = Res.string.question_597,
            image = "x",
            answers = listOf(
                Res.string.question_597_answer_1,
                Res.string.question_597_answer_2,
                Res.string.question_597_answer_3
            ),
            trueAnswer = Res.string.question_597_true_answer
        ),

        Question(
            question = Res.string.question_598,
            image = "x",
            answers = listOf(
                Res.string.question_598_answer_1,
                Res.string.question_598_answer_2
            ),
            trueAnswer = Res.string.question_598_true_answer
        ),

        Question(
            question = Res.string.question_599,
            image = "x",
            answers = listOf(
                Res.string.question_599_answer_1,
                Res.string.question_599_answer_2
            ),
            trueAnswer = Res.string.question_599_true_answer
        ),
        Question(
            question = Res.string.question_600,
            image = "x",
            answers = listOf(
                Res.string.question_600_answer_1,
                Res.string.question_600_answer_2
            ),
            trueAnswer = Res.string.question_600_true_answer
        ),

        Question(
            question = Res.string.question_601,
            image = "x",
            answers = listOf(
                Res.string.question_601_answer_1,
                Res.string.question_601_answer_2,
                Res.string.question_601_answer_3
            ),
            trueAnswer = Res.string.question_601_true_answer
        ),

        Question(
            question = Res.string.question_602,
            image = "x",
            answers = listOf(
                Res.string.question_602_answer_1,
                Res.string.question_602_answer_2,
                Res.string.question_602_answer_3
            ),
            trueAnswer = Res.string.question_602_true_answer
        ),

        Question(
            question = Res.string.question_603,
            image = "x",
            answers = listOf(
                Res.string.question_603_answer_1,
                Res.string.question_603_answer_2,
                Res.string.question_603_answer_3
            ),
            trueAnswer = Res.string.question_603_true_answer
        ),

        Question(
            question = Res.string.question_604,
            image = "x",
            answers = listOf(
                Res.string.question_604_answer_1,
                Res.string.question_604_answer_2,
                Res.string.question_604_answer_3,
                Res.string.question_604_answer_4
            ),
            trueAnswer = Res.string.question_604_true_answer
        ),

        Question(
            question = Res.string.question_605,
            image = "x",
            answers = listOf(
                Res.string.question_605_answer_1,
                Res.string.question_605_answer_2,
                Res.string.question_605_answer_3
            ),
            trueAnswer = Res.string.question_605_true_answer
        ),

        Question(
            question = Res.string.question_606,
            image = "x",
            answers = listOf(
                Res.string.question_606_answer_1,
                Res.string.question_606_answer_2,
                Res.string.question_606_answer_3
            ),
            trueAnswer = Res.string.question_606_true_answer
        ),

        Question(
            question = Res.string.question_607,
            image = "x",
            answers = listOf(
                Res.string.question_607_answer_1,
                Res.string.question_607_answer_2,
                Res.string.question_607_answer_3,
                Res.string.question_607_answer_4
            ),
            trueAnswer = Res.string.question_607_true_answer
        ),

        Question(
            question = Res.string.question_608,
            image = "x",
            answers = listOf(
                Res.string.question_608_answer_1,
                Res.string.question_608_answer_2,
                Res.string.question_608_answer_3
            ),
            trueAnswer = Res.string.question_608_true_answer
        ),
    )
}